package com.thedazzler.droidicon;

import com.thedazzler.droidicon.util.TypefaceManager;

import java.util.HashMap;
import java.util.Map;

/**
 * Created by Devon Guinane on 11/15/14.
 * Droidicon
 */
public class Droidicon
{
    private static Map<String, Integer> iconMap = new HashMap<String, Integer>();

    static {
        //FontAwesome
        iconMap.put("fa-glass", 0xF000);
        iconMap.put("fa-music", 0xf001);
        iconMap.put("fa-search", 0xf002);
        iconMap.put("fa-envelope-o", 0xf003);
        iconMap.put("fa-heart", 0xf004);
        iconMap.put("fa-star", 0xf005);
        iconMap.put("fa-star-o", 0xf006);
        iconMap.put("fa-user", 0xf007);
        iconMap.put("fa-film", 0xf008);
        iconMap.put("fa-th-large", 0xf009);
        iconMap.put("fa-th", 0xf00a);
        iconMap.put("fa-th-list", 0xf00b);
        iconMap.put("fa-check", 0xf00c);
        iconMap.put("fa-times", 0xf00d);
        iconMap.put("fa-search-plus", 0xf00e);
        iconMap.put("fa-search-minus", 0xf010);
        iconMap.put("fa-power-off", 0xf011);
        iconMap.put("fa-signal", 0xf012);
        iconMap.put("fa-cog", 0xf013);
        iconMap.put("fa-trash-o", 0xf014);
        iconMap.put("fa-home", 0xf015);
        iconMap.put("fa-file-o", 0xf016);
        iconMap.put("fa-clock-o", 0xf017);
        iconMap.put("fa-road", 0xf018);
        iconMap.put("fa-download", 0xf019);
        iconMap.put("fa-arrow-circle-o-down", 0xf01a);
        iconMap.put("fa-arrow-circle-o-up", 0xf01b);
        iconMap.put("fa-inbox", 0xf01c);
        iconMap.put("fa-play-circle-o", 0xf01d);
        iconMap.put("fa-repeat", 0xf01e);
        iconMap.put("fa-refresh", 0xf021);
        iconMap.put("fa-list-alt", 0xf022);
        iconMap.put("fa-lock", 0xf023);
        iconMap.put("fa-flag", 0xf024);
        iconMap.put("fa-headphones", 0xf025);
        iconMap.put("fa-volume-off", 0xf026);
        iconMap.put("fa-volume-down", 0xf027);
        iconMap.put("fa-volume-up", 0xf028);
        iconMap.put("fa-qrcode", 0xf029);
        iconMap.put("fa-barcode", 0xf02a);
        iconMap.put("fa-tag", 0xf02b);
        iconMap.put("fa-tags", 0xf02c);
        iconMap.put("fa-book", 0xf02d);
        iconMap.put("fa-bookmark", 0xf02e);
        iconMap.put("fa-print", 0xf02f);
        iconMap.put("fa-camera", 0xf030);
        iconMap.put("fa-font", 0xf031);
        iconMap.put("fa-bold", 0xf032);
        iconMap.put("fa-italic", 0xf033);
        iconMap.put("fa-text-height", 0xf034);
        iconMap.put("fa-text-width", 0xf035);
        iconMap.put("fa-align-left", 0xf036);
        iconMap.put("fa-align-center", 0xf037);
        iconMap.put("fa-align-right", 0xf038);
        iconMap.put("fa-align-justify", 0xf039);
        iconMap.put("fa-list", 0xf03a);
        iconMap.put("fa-outdent", 0xf03b);
        iconMap.put("fa-indent", 0xf03c);
        iconMap.put("fa-video-camera", 0xf03d);
        iconMap.put("fa-picture-o", 0xf03e);
        iconMap.put("fa-pencil", 0xf040);
        iconMap.put("fa-map-marker", 0xf041);
        iconMap.put("fa-adjust", 0xf042);
        iconMap.put("fa-tint", 0xf043);
        iconMap.put("fa-pencil-square-o", 0xf044);
        iconMap.put("fa-share-square-o", 0xf045);
        iconMap.put("fa-check-square-o", 0xf046);
        iconMap.put("fa-move", 0xf047);
        iconMap.put("fa-step-backward", 0xf048);
        iconMap.put("fa-fast-backward", 0xf049);
        iconMap.put("fa-backward", 0xf04a);
        iconMap.put("fa-play", 0xf04b);
        iconMap.put("fa-pause", 0xf04c);
        iconMap.put("fa-stop", 0xf04d);
        iconMap.put("fa-forward", 0xf04e);
        iconMap.put("fa-fast-forward", 0xf050);
        iconMap.put("fa-step-forward", 0xf051);
        iconMap.put("fa-eject", 0xf052);
        iconMap.put("fa-chevron-left", 0xf053);
        iconMap.put("fa-chevron-right", 0xf054);
        iconMap.put("fa-plus-circle", 0xf055);
        iconMap.put("fa-minus-circle", 0xf056);
        iconMap.put("fa-times-circle", 0xf057);
        iconMap.put("fa-check-circle", 0xf058);
        iconMap.put("fa-question-circle", 0xf059);
        iconMap.put("fa-info-circle", 0xf05a);
        iconMap.put("fa-crosshairs", 0xf05b);
        iconMap.put("fa-times-circle-o", 0xf05c);
        iconMap.put("fa-check-circle-o", 0xf05d);
        iconMap.put("fa-ban", 0xf05e);
        iconMap.put("fa-arrow-left", 0xf060);
        iconMap.put("fa-arrow-right", 0xf061);
        iconMap.put("fa-arrow-up", 0xf062);
        iconMap.put("fa-arrow-down", 0xf063);
        iconMap.put("fa-share", 0xf064);
        iconMap.put("fa-resize-full", 0xf065);
        iconMap.put("fa-resize-small", 0xf066);
        iconMap.put("fa-plus", 0xf067);
        iconMap.put("fa-minus", 0xf068);
        iconMap.put("fa-asterisk", 0xf069);
        iconMap.put("fa-exclamation-circle", 0xf06a);
        iconMap.put("fa-gift", 0xf06b);
        iconMap.put("fa-leaf", 0xf06c);
        iconMap.put("fa-fire", 0xf06d);
        iconMap.put("fa-eye", 0xf06e);
        iconMap.put("fa-eye-slash", 0xf070);
        iconMap.put("fa-exclamation-triangle", 0xf071);
        iconMap.put("fa-plane", 0xf072);
        iconMap.put("fa-calendar", 0xf073);
        iconMap.put("fa-random", 0xf074);
        iconMap.put("fa-comment", 0xf075);
        iconMap.put("fa-magnet", 0xf076);
        iconMap.put("fa-chevron-up", 0xf077);
        iconMap.put("fa-chevron-down", 0xf078);
        iconMap.put("fa-retweet", 0xf079);
        iconMap.put("fa-shopping-cart", 0xf07a);
        iconMap.put("fa-folder", 0xf07b);
        iconMap.put("fa-folder-open", 0xf07c);
        iconMap.put("fa-resize-vertical", 0xf07d);
        iconMap.put("fa-resize-horizontal", 0xf07e);
        iconMap.put("fa-bar-chart-o", 0xf080);
        iconMap.put("fa-twitter-square", 0xf081);
        iconMap.put("fa-facebook-square", 0xf082);
        iconMap.put("fa-camera-retro", 0xf083);
        iconMap.put("fa-key", 0xf084);
        iconMap.put("fa-cogs", 0xf085);
        iconMap.put("fa-comments", 0xf086);
        iconMap.put("fa-thumbs-o-up", 0xf087);
        iconMap.put("fa-thumbs-o-down", 0xf088);
        iconMap.put("fa-star-half", 0xf089);
        iconMap.put("fa-heart-o", 0xf08a);
        iconMap.put("fa-sign-out", 0xf08b);
        iconMap.put("fa-linkedin-square", 0xf08c);
        iconMap.put("fa-thumb-tack", 0xf08d);
        iconMap.put("fa-external-link", 0xf08e);
        iconMap.put("fa-sign-in", 0xf090);
        iconMap.put("fa-trophy", 0xf091);
        iconMap.put("fa-github-square", 0xf092);
        iconMap.put("fa-upload", 0xf093);
        iconMap.put("fa-lemon-o", 0xf094);
        iconMap.put("fa-phone", 0xf095);
        iconMap.put("fa-square-o", 0xf096);
        iconMap.put("fa-bookmark-o", 0xf097);
        iconMap.put("fa-phone-square", 0xf098);
        iconMap.put("fa-twitter", 0xf099);
        iconMap.put("fa-facebook", 0xf09a);
        iconMap.put("fa-github", 0xf09b);
        iconMap.put("fa-unlock", 0xf09c);
        iconMap.put("fa-credit-card", 0xf09d);
        iconMap.put("fa-rss", 0xf09e);
        iconMap.put("fa-hdd", 0xf0a0);
        iconMap.put("fa-bullhorn", 0xf0a1);
        iconMap.put("fa-bell", 0xf0f3);
        iconMap.put("fa-certificate", 0xf0a3);
        iconMap.put("fa-hand-o-right", 0xf0a4);
        iconMap.put("fa-hand-o-left", 0xf0a5);
        iconMap.put("fa-hand-o-up", 0xf0a6);
        iconMap.put("fa-hand-o-down", 0xf0a7);
        iconMap.put("fa-arrow-circle-left", 0xf0a8);
        iconMap.put("fa-arrow-circle-right", 0xf0a9);
        iconMap.put("fa-arrow-circle-up", 0xf0aa);
        iconMap.put("fa-arrow-circle-down", 0xf0ab);
        iconMap.put("fa-globe", 0xf0ac);
        iconMap.put("fa-wrench", 0xf0ad);
        iconMap.put("fa-tasks", 0xf0ae);
        iconMap.put("fa-filter", 0xf0b0);
        iconMap.put("fa-briefcase", 0xf0b1);
        iconMap.put("fa-fullscreen", 0xf0b2);
        iconMap.put("fa-group", 0xf0c0);
        iconMap.put("fa-link", 0xf0c1);
        iconMap.put("fa-cloud", 0xf0c2);
        iconMap.put("fa-flask", 0xf0c3);
        iconMap.put("fa-scissors", 0xf0c4);
        iconMap.put("fa-files-o", 0xf0c5);
        iconMap.put("fa-paperclip", 0xf0c6);
        iconMap.put("fa-floppy-o", 0xf0c7);
        iconMap.put("fa-square", 0xf0c8);
        iconMap.put("fa-reorder", 0xf0c9);
        iconMap.put("fa-list-ul", 0xf0ca);
        iconMap.put("fa-list-ol", 0xf0cb);
        iconMap.put("fa-strikethrough", 0xf0cc);
        iconMap.put("fa-underline", 0xf0cd);
        iconMap.put("fa-table", 0xf0ce);
        iconMap.put("fa-magic", 0xf0d0);
        iconMap.put("fa-truck", 0xf0d1);
        iconMap.put("fa-pinterest", 0xf0d2);
        iconMap.put("fa-pinterest-square", 0xf0d3);
        iconMap.put("fa-google-plus-square", 0xf0d4);
        iconMap.put("fa-google-plus", 0xf0d5);
        iconMap.put("fa-money", 0xf0d6);
        iconMap.put("fa-caret-down", 0xf0d7);
        iconMap.put("fa-caret-up", 0xf0d8);
        iconMap.put("fa-caret-left", 0xf0d9);
        iconMap.put("fa-caret-right", 0xf0da);
        iconMap.put("fa-columns", 0xf0db);
        iconMap.put("fa-sort", 0xf0dc);
        iconMap.put("fa-sort-asc", 0xf0dd);
        iconMap.put("fa-sort-desc", 0xf0de);
        iconMap.put("fa-envelope", 0xf0e0);
        iconMap.put("fa-linkedin", 0xf0e1);
        iconMap.put("fa-undo", 0xf0e2);
        iconMap.put("fa-gavel", 0xf0e3);
        iconMap.put("fa-tachometer", 0xf0e4);
        iconMap.put("fa-comment-o", 0xf0e5);
        iconMap.put("fa-comments-o", 0xf0e6);
        iconMap.put("fa-bolt", 0xf0e7);
        iconMap.put("fa-sitemap", 0xf0e8);
        iconMap.put("fa-umbrella", 0xf0e9);
        iconMap.put("fa-clipboard", 0xf0ea);
        iconMap.put("fa-lightbulb-o", 0xf0eb);
        iconMap.put("fa-exchange", 0xf0ec);
        iconMap.put("fa-cloud-download", 0xf0ed);
        iconMap.put("fa-cloud-upload", 0xf0ee);
        iconMap.put("fa-user-md", 0xf0f0);
        iconMap.put("fa-stethoscope", 0xf0f1);
        iconMap.put("fa-suitcase", 0xf0f2);
        iconMap.put("fa-bell-o", 0xf0a2);
        iconMap.put("fa-coffee", 0xf0f4);
        iconMap.put("fa-cutlery", 0xf0f5);
        iconMap.put("fa-file-text-o", 0xf0f6);
        iconMap.put("fa-building", 0xf0f7);
        iconMap.put("fa-hospital", 0xf0f8);
        iconMap.put("fa-ambulance", 0xf0f9);
        iconMap.put("fa-medkit", 0xf0fa);
        iconMap.put("fa-fighter-jet", 0xf0fb);
        iconMap.put("fa-beer", 0xf0fc);
        iconMap.put("fa-h-square", 0xf0fd);
        iconMap.put("fa-plus-square", 0xf0fe);
        iconMap.put("fa-angle-double-left", 0xf100);
        iconMap.put("fa-angle-double-right", 0xf101);
        iconMap.put("fa-angle-double-up", 0xf102);
        iconMap.put("fa-angle-double-down", 0xf103);
        iconMap.put("fa-angle-left", 0xf104);
        iconMap.put("fa-angle-right", 0xf105);
        iconMap.put("fa-angle-up", 0xf106);
        iconMap.put("fa-angle-down", 0xf107);
        iconMap.put("fa-desktop", 0xf108);
        iconMap.put("fa-laptop", 0xf109);
        iconMap.put("fa-tablet", 0xf10a);
        iconMap.put("fa-mobile", 0xf10b);
        iconMap.put("fa-circle-o", 0xf10c);
        iconMap.put("fa-quote-left", 0xf10d);
        iconMap.put("fa-quote-right", 0xf10e);
        iconMap.put("fa-spinner", 0xf110);
        iconMap.put("fa-circle", 0xf111);
        iconMap.put("fa-reply", 0xf112);
        iconMap.put("fa-github-alt", 0xf113);
        iconMap.put("fa-folder-o", 0xf114);
        iconMap.put("fa-folder-open-o", 0xf115);
        iconMap.put("fa-expand-o", 0xf116);
        iconMap.put("fa-collapse-o", 0xf117);
        iconMap.put("fa-smile-o", 0xf118);
        iconMap.put("fa-frown-o", 0xf119);
        iconMap.put("fa-meh-o", 0xf11a);
        iconMap.put("fa-gamepad", 0xf11b);
        iconMap.put("fa-keyboard-o", 0xf11c);
        iconMap.put("fa-flag-o", 0xf11d);
        iconMap.put("fa-flag-checkered", 0xf11e);
        iconMap.put("fa-terminal", 0xf120);
        iconMap.put("fa-code", 0xf121);
        iconMap.put("fa-reply-all", 0xf122);
        iconMap.put("fa-mail-reply-all", 0xf122);
        iconMap.put("fa-star-half-o", 0xf123);
        iconMap.put("fa-location-arrow", 0xf124);
        iconMap.put("fa-crop", 0xf125);
        iconMap.put("fa-code-fork", 0xf126);
        iconMap.put("fa-chain-broken", 0xf127);
        iconMap.put("fa-question", 0xf128);
        iconMap.put("fa-info", 0xf129);
        iconMap.put("fa-exclamation", 0xf12a);
        iconMap.put("fa-superscript", 0xf12b);
        iconMap.put("fa-subscript", 0xf12c);
        iconMap.put("fa-eraser", 0xf12d);
        iconMap.put("fa-puzzle-piece", 0xf12e);
        iconMap.put("fa-microphone", 0xf130);
        iconMap.put("fa-microphone-slash", 0xf131);
        iconMap.put("fa-shield", 0xf132);
        iconMap.put("fa-calendar-o", 0xf133);
        iconMap.put("fa-fire-extinguisher", 0xf134);
        iconMap.put("fa-rocket", 0xf135);
        iconMap.put("fa-maxcdn", 0xf136);
        iconMap.put("fa-chevron-circle-left", 0xf137);
        iconMap.put("fa-chevron-circle-right", 0xf138);
        iconMap.put("fa-chevron-circle-up", 0xf139);
        iconMap.put("fa-chevron-circle-down", 0xf13a);
        iconMap.put("fa-html5", 0xf13b);
        iconMap.put("fa-css3", 0xf13c);
        iconMap.put("fa-anchor", 0xf13d);
        iconMap.put("fa-unlock-o", 0xf13e);
        iconMap.put("fa-bullseye", 0xf140);
        iconMap.put("fa-ellipsis-horizontal", 0xf141);
        iconMap.put("fa-ellipsis-vertical", 0xf142);
        iconMap.put("fa-rss-square", 0xf143);
        iconMap.put("fa-play-circle", 0xf144);
        iconMap.put("fa-ticket", 0xf145);
        iconMap.put("fa-minus-square", 0xf146);
        iconMap.put("fa-minus-square-o", 0xf147);
        iconMap.put("fa-level-up", 0xf148);
        iconMap.put("fa-level-down", 0xf149);
        iconMap.put("fa-check-square", 0xf14a);
        iconMap.put("fa-pencil-square", 0xf14b);
        iconMap.put("fa-external-link-square", 0xf14c);
        iconMap.put("fa-share-square", 0xf14d);
        iconMap.put("fa-compass", 0xf14e);
        iconMap.put("fa-caret-square-o-down", 0xf150);
        iconMap.put("fa-caret-square-o-up", 0xf151);
        iconMap.put("fa-caret-square-o-right", 0xf152);
        iconMap.put("fa-eur", 0xf153);
        iconMap.put("fa-gbp", 0xf154);
        iconMap.put("fa-usd", 0xf155);
        iconMap.put("fa-inr", 0xf156);
        iconMap.put("fa-jpy", 0xf157);
        iconMap.put("fa-rub", 0xf158);
        iconMap.put("fa-krw", 0xf159);
        iconMap.put("fa-btc", 0xf15a);
        iconMap.put("fa-file", 0xf15b);
        iconMap.put("fa-file-text", 0xf15c);
        iconMap.put("fa-sort-alpha-asc", 0xf15d);
        iconMap.put("fa-sort-alpha-desc", 0xf15e);
        iconMap.put("fa-sort-amount-asc", 0xf160);
        iconMap.put("fa-sort-amount-desc", 0xf161);
        iconMap.put("fa-sort-numeric-asc", 0xf162);
        iconMap.put("fa-sort-numeric-desc", 0xf163);
        iconMap.put("fa-thumbs-up", 0xf164);
        iconMap.put("fa-thumbs-down", 0xf165);
        iconMap.put("fa-youtube-square", 0xf166);
        iconMap.put("fa-youtube", 0xf167);
        iconMap.put("fa-xing", 0xf168);
        iconMap.put("fa-xing-square", 0xf169);
        iconMap.put("fa-youtube-play", 0xf16a);
        iconMap.put("fa-dropbox", 0xf16b);
        iconMap.put("fa-stack-overflow", 0xf16c);
        iconMap.put("fa-instagram", 0xf16d);
        iconMap.put("fa-flickr", 0xf16e);
        iconMap.put("fa-adn", 0xf170);
        iconMap.put("fa-bitbucket", 0xf171);
        iconMap.put("fa-bitbucket-square", 0xf172);
        iconMap.put("fa-tumblr", 0xf173);
        iconMap.put("fa-tumblr-square", 0xf174);
        iconMap.put("fa-long-arrow-down", 0xf175);
        iconMap.put("fa-long-arrow-up", 0xf176);
        iconMap.put("fa-long-arrow-left", 0xf177);
        iconMap.put("fa-long-arrow-right", 0xf178);
        iconMap.put("fa-apple", 0xf179);
        iconMap.put("fa-windows", 0xf17a);
        iconMap.put("fa-android", 0xf17b);
        iconMap.put("fa-linux", 0xf17c);
        iconMap.put("fa-dribbble", 0xf17d);
        iconMap.put("fa-skype", 0xf17e);
        iconMap.put("fa-foursquare", 0xf180);
        iconMap.put("fa-trello", 0xf181);
        iconMap.put("fa-female", 0xf182);
        iconMap.put("fa-male", 0xf183);
        iconMap.put("fa-gittip", 0xf184);
        iconMap.put("fa-sun-o", 0xf185);
        iconMap.put("fa-moon-o", 0xf186);
        iconMap.put("fa-archive", 0xf187);
        iconMap.put("fa-bug", 0xf188);
        iconMap.put("fa-vk", 0xf189);
        iconMap.put("fa-weibo", 0xf18a);
        iconMap.put("fa-renren", 0xf18b);
        iconMap.put("fa-pagelines", 0xf18c);
        iconMap.put("fa-stack-exchange", 0xf18d);
        iconMap.put("fa-arrow-circle-o-right", 0xf18e);
        iconMap.put("fa-arrow-circle-o-left", 0xf190);
        iconMap.put("fa-caret-square-o-left", 0xf191);
        iconMap.put("fa-dot-circle-o", 0xf192);
        iconMap.put("fa-wheelchair", 0xf193);
        iconMap.put("fa-vimeo-square", 0xf194);

        iconMap.put("fa-space-shuttle", 0xf197);
        iconMap.put("fa-graduation-cap", 0xf19d);
        iconMap.put("fa-child",0xf1ae);
        iconMap.put("fa-bomb", 0xf1e2);
        iconMap.put("fa-soccer-ball-o", 0xf1e3);
        iconMap.put("fa-angelist", 0xf209);
        iconMap.put("fa-area-chart", 0xf1fe);
        iconMap.put("fa-at", 0xf1fa);
        iconMap.put("fa-bell-slash", 0xf1f6);
        iconMap.put("fa-bell-slash-o", 0xf0a2);
        iconMap.put("fa-bicycle", 0xf206);
        iconMap.put("fa-binoculars", 0xf1e5);
        iconMap.put("fa-birthday-cake", 0xf1fd);
        iconMap.put("fa-bus", 0xf207);
        iconMap.put("fa-calculator", 0xf1ec);
        iconMap.put("fa-cc", 0xf20a);
        iconMap.put("fa-cc-amex", 0xf1f3);
        iconMap.put("fa-cc-discover", 0xf1f2);
        iconMap.put("fa-cc-mastercard", 0xf1f1);
        iconMap.put("fa-cc-paypal", 0xf1f4);
        iconMap.put("fa-cc-stripe", 0xf1f5);
        iconMap.put("fa-cc-visa", 0xf1f0);
        iconMap.put("fa-copyright", 0xf1f9);
        iconMap.put("fa-eyedropper", 0xf1fb);
        iconMap.put("fa-futbol-o", 0xf1e3);
        iconMap.put("fa-google-wallet", 0xf1ee);
        iconMap.put("fa-ils", 0xf20b);
        iconMap.put("fa-ioxhost", 0xf208);
        iconMap.put("fa-lastfm", 0xf202);
        iconMap.put("fa-lastfm-square", 0xf203);
        iconMap.put("fa-line-chart", 0xf201);
        iconMap.put("fa-meanpath", 0xf20c);
        iconMap.put("fa-newspaper-o", 0xf1ea);
        iconMap.put("fa-paint-brush", 0xf1fc);
        iconMap.put("fa-paypal", 0xf1ed);
        iconMap.put("fa-pie-chart", 0xf200);
        iconMap.put("fa-plug", 0xf1e6);
        iconMap.put("fa-shekel", 0xf20b);
        iconMap.put("fa-sheqel", 0xf20b);
        iconMap.put("fa-slideshare", 0xf1e7);
        iconMap.put("fa-toggle-off", 0xf204);
        iconMap.put("fa-toggle-on", 0xf205);
        iconMap.put("fa-trash", 0xf1f8);
        iconMap.put("fa-tty", 0xf1e4);
        iconMap.put("fa-twitch", 0xf1e8);
        iconMap.put("fa-wifi", 0xf1eb);
        iconMap.put("fa-yelp", 0xf1e9);






        //Entypo
        iconMap.put("entypo-phone", 0x1F4DE);
        iconMap.put("entypo-mobile", 0x1F4F1);
        iconMap.put("entypo-mouse", 0xE789);
        iconMap.put("entypo-address", 0xE723);
        iconMap.put("entypo-mail", 0x2709);
        iconMap.put("entypo-paper-plane", 0x1F53F);
        iconMap.put("entypo-pencil", 0x270E);
        iconMap.put("entypo-feather", 0x2712);
        iconMap.put("entypo-attach", 0x1F4CE);
        iconMap.put("entypo-inbox", 0xE777);
        iconMap.put("entypo-reply", 0xE712);
        iconMap.put("entypo-reply-all", 0xE713);
        iconMap.put("entypo-forward", 0x27A6);
        iconMap.put("entypo-user", 0x1F464);
        iconMap.put("entypo-users", 0x1F465);
        iconMap.put("entypo-add-user", 0xE700);
        iconMap.put("entypo-vcard", 0xE722);
        iconMap.put("entypo-export", 0xE715);
        iconMap.put("entypo-location", 0xE724);
        iconMap.put("entypo-map", 0xE727);
        iconMap.put("entypo-compass", 0xE728);
        iconMap.put("entypo-direction", 0x27A2);
        iconMap.put("entypo-hair-cross", 0x1F3AF);
        iconMap.put("entypo-share", 0xE73C);
        iconMap.put("entypo-shareable", 0xE73E);
        iconMap.put("entypo-heart", 0x2665);
        iconMap.put("entypo-heart-empty", 0x2661);
        iconMap.put("entypo-star", 0x2605);
        iconMap.put("entypo-star-empty", 0x2606);
        iconMap.put("entypo-thumbs-up", 0x1F44D);
        iconMap.put("entypo-thumbs-down", 0x1F44E);
        iconMap.put("entypo-chat", 0xE720);
        iconMap.put("entypo-comment", 0xE718);
        iconMap.put("entypo-quote", 0x275E);
        iconMap.put("entypo-home", 0x2302);
        iconMap.put("entypo-popup", 0xE74C);
        iconMap.put("entypo-search", 0x1F50D);
        iconMap.put("entypo-flashlight", 0x1F526);
        iconMap.put("entypo-print", 0xE716);
        iconMap.put("entypo-bell", 0x1F514);
        iconMap.put("entypo-link", 0x1F517);
        iconMap.put("entypo-flag", 0x2691);
        iconMap.put("entypo-cog", 0x2699);
        iconMap.put("entypo-tools", 0x2692);
        iconMap.put("entypo-trophy", 0x1F3C6);
        iconMap.put("entypo-tag", 0xE70C);
        iconMap.put("entypo-camera", 0x1F4F7);
        iconMap.put("entypo-megaphone", 0x1F4E3);
        iconMap.put("entypo-moon", 0x263D);
        iconMap.put("entypo-palette", 0x1F3A8);
        iconMap.put("entypo-leaf", 0x1F342);
        iconMap.put("entypo-note", 0x266A);
        iconMap.put("entypo-beamed-note", 0x266B);
        iconMap.put("entypo-new", 0x1F4A5);
        iconMap.put("entypo-graduation-cap", 0x1F393);
        iconMap.put("entypo-book", 0x1F4D5);
        iconMap.put("entypo-newspaper", 0x1F4F0);
        iconMap.put("entypo-bag", 0x1F45C);
        iconMap.put("entypo-airplane", 0x2708);
        iconMap.put("entypo-lifebuoy", 0xE788);
        iconMap.put("entypo-eye", 0xE70A);
        iconMap.put("entypo-clock", 0x1F554);
        iconMap.put("entypo-mic", 0x1F3A4);
        iconMap.put("entypo-calendar", 0x1F4C5);
        iconMap.put("entypo-flash", 0x26A1);
        iconMap.put("entypo-thunder-cloud", 0x26C8);
        iconMap.put("entypo-droplet", 0x1F4A7);
        iconMap.put("entypo-cd", 0x1F4BF);
        iconMap.put("entypo-briefcase", 0x1F4BC);
        iconMap.put("entypo-air", 0x1F4A8);
        iconMap.put("entypo-hourglass", 0x23F3);
        iconMap.put("entypo-gauge", 0x1F6C7);
        iconMap.put("entypo-language", 0x1F394);
        iconMap.put("entypo-network", 0xE776);
        iconMap.put("entypo-key", 0x1F511);
        iconMap.put("entypo-battery", 0x1F50B);
        iconMap.put("entypo-bucket", 0x1F4FE);
        iconMap.put("entypo-magnet", 0xE7A1);
        iconMap.put("entypo-drive", 0x1F4FD);
        iconMap.put("entypo-cup", 0x2615);
        iconMap.put("entypo-rocket", 0x1F680);
        iconMap.put("entypo-brush", 0xE79A);
        iconMap.put("entypo-suitcase", 0x1F6C6);
        iconMap.put("entypo-traffic-cone", 0x1F6C8);
        iconMap.put("entypo-globe", 0x1F30E);
        iconMap.put("entypo-keyboard", 0x2328);
        iconMap.put("entypo-browser", 0xE74E);
        iconMap.put("entypo-publish", 0xE74D);
        iconMap.put("entypo-progress-3", 0xE76B);
        iconMap.put("entypo-progress-2", 0xE76A);
        iconMap.put("entypo-progress-1", 0xE769);
        iconMap.put("entypo-progress-0", 0xE768);
        iconMap.put("entypo-light-down", 0x1F505);
        iconMap.put("entypo-light-up", 0x1F506);
        iconMap.put("entypo-adjust", 0x25D1);
        iconMap.put("entypo-code", 0xE714);
        iconMap.put("entypo-monitor", 0x1F4BB);
        iconMap.put("entypo-infinity", 0x221E);
        iconMap.put("entypo-light-bulb", 0x1F4A1);
        iconMap.put("entypo-credit-card", 0x1F4B3);
        iconMap.put("entypo-database", 0x1F4F8);
        iconMap.put("entypo-voicemail", 0x2707);
        iconMap.put("entypo-clipboard", 0x1F4CB);
        iconMap.put("entypo-cart", 0xE73D);
        iconMap.put("entypo-box", 0x1F4E6);
        iconMap.put("entypo-ticket", 0x1F3AB);
        iconMap.put("entypo-rss", 0xE73A);
        iconMap.put("entypo-signal", 0x1F4F6);
        iconMap.put("entypo-thermometer", 0x1F4FF);
        iconMap.put("entypo-water", 0x1F4A6);
        iconMap.put("entypo-sweden", 0xF601);
        iconMap.put("entypo-line-graph", 0x1F4C8);
        iconMap.put("entypo-pie-chart", 0x25F4);
        iconMap.put("entypo-bar-graph", 0x1F4CA);
        iconMap.put("entypo-area-graph", 0x1F53E);
        iconMap.put("entypo-lock", 0x1F512);
        iconMap.put("entypo-lock-open", 0x1F513);
        iconMap.put("entypo-logout", 0xE741);
        iconMap.put("entypo-login", 0xE740);
        iconMap.put("entypo-check", 0x2713);
        iconMap.put("entypo-cross", 0x274C);
        iconMap.put("entypo-squared-minus", 0x229F);
        iconMap.put("entypo-squared-plus", 0x229E);
        iconMap.put("entypo-squared-cross", 0x274E);
        iconMap.put("entypo-circled-minus", 0x2296);
        iconMap.put("entypo-circled-plus", 0x2295);
        iconMap.put("entypo-circled-cross", 0x2716);
        iconMap.put("entypo-minus", 0x2796);
        iconMap.put("entypo-plus", 0x2795);
        iconMap.put("entypo-erase", 0x232B);
        iconMap.put("entypo-block", 0x1F6AB);
        iconMap.put("entypo-info", 0x2139);
        iconMap.put("entypo-circled-info", 0xE705);
        iconMap.put("entypo-help", 0x2753);
        iconMap.put("entypo-circled-help", 0xE704);
        iconMap.put("entypo-warning", 0x26A0);
        iconMap.put("entypo-cycle", 0x1F504);
        iconMap.put("entypo-cw", 0x27F3);
        iconMap.put("entypo-ccw", 0x27F2);
        iconMap.put("entypo-shuffle", 0x1F500);
        iconMap.put("entypo-back", 0x1F519);
        iconMap.put("entypo-level-down", 0x21B3);
        iconMap.put("entypo-retweet", 0xE717);
        iconMap.put("entypo-loop", 0x1F501);
        iconMap.put("entypo-back-in-time", 0xE771);
        iconMap.put("entypo-level-up", 0x21B0);
        iconMap.put("entypo-switch", 0x21C6);
        iconMap.put("entypo-numbered-list", 0xE005);
        iconMap.put("entypo-add-to-list", 0xE003);
        iconMap.put("entypo-layout", 0x268F);
        iconMap.put("entypo-list", 0x2630);
        iconMap.put("entypo-text-doc", 0x1F4C4);
        iconMap.put("entypo-text-doc-inverted", 0xE731);
        iconMap.put("entypo-doc", 0xE730);
        iconMap.put("entypo-docs", 0xE736);
        iconMap.put("entypo-landscape-doc", 0xE737);
        iconMap.put("entypo-picture", 0x1F304);
        iconMap.put("entypo-video", 0x1F3AC);
        iconMap.put("entypo-music", 0x1F3B5);
        iconMap.put("entypo-folder", 0x1F4C1);
        iconMap.put("entypo-archive", 0xE800);
        iconMap.put("entypo-trash", 0xE729);
        iconMap.put("entypo-upload", 0x1F4E4);
        iconMap.put("entypo-download", 0x1F4E5);
        iconMap.put("entypo-save", 0x1F4BE);
        iconMap.put("entypo-install", 0xE778);
        iconMap.put("entypo-cloud", 0x2601);
        iconMap.put("entypo-upload-cloud", 0xE711);
        iconMap.put("entypo-bookmark", 0x1F516);
        iconMap.put("entypo-bookmarks", 0x1F4D1);
        iconMap.put("entypo-open-book", 0x1F4D6);
        iconMap.put("entypo-play", 0x25B6);
        iconMap.put("entypo-pause", 0x2016);
        iconMap.put("entypo-record", 0x25CF);
        iconMap.put("entypo-stop", 0x25A0);
        iconMap.put("entypo-ff", 0x23E9);
        iconMap.put("entypo-fb", 0x23EA);
        iconMap.put("entypo-to-start", 0x23EE);
        iconMap.put("entypo-to-end", 0x23ED);
        iconMap.put("entypo-resize-full", 0xE744);
        iconMap.put("entypo-resize-small", 0xE746);
        iconMap.put("entypo-volume", 0x23F7);
        iconMap.put("entypo-sound", 0x1F50A);
        iconMap.put("entypo-mute", 0x1F507);
        iconMap.put("entypo-flow-cascade", 0x1F568);
        iconMap.put("entypo-branch", 0x1F569);
        iconMap.put("entypo-flow-tree", 0x1F56A);
        iconMap.put("entypo-flow-line", 0x1F56B);
        iconMap.put("entypo-flow-parallel", 0x1F56C);
        iconMap.put("entypo-left-bold", 0xE4AD);
        iconMap.put("entypo-down-bold", 0xE4B0);
        iconMap.put("entypo-up-bold", 0xE4AF);
        iconMap.put("entypo-right-bold", 0xE4AE);
        iconMap.put("entypo-left", 0x2B05);
        iconMap.put("entypo-down", 0x2B07);
        iconMap.put("entypo-up", 0x2B06);
        iconMap.put("entypo-right", 0x27A1);
        iconMap.put("entypo-circled-left", 0xE759);
        iconMap.put("entypo-circled-down", 0xE758);
        iconMap.put("entypo-circled-up", 0xE75B);
        iconMap.put("entypo-circled-right", 0xE75A);
        iconMap.put("entypo-triangle-left", 0x25C2);
        iconMap.put("entypo-triangle-down", 0x25BE);
        iconMap.put("entypo-triangle-up", 0x25B4);
        iconMap.put("entypo-triangle-right", 0x25B8);
        iconMap.put("entypo-chevron-left", 0xE75D);
        iconMap.put("entypo-chevron-down", 0xE75C);
        iconMap.put("entypo-chevron-up", 0xE75F);
        iconMap.put("entypo-chevron-right", 0xE75E);
        iconMap.put("entypo-chevron-small-left", 0xE761);
        iconMap.put("entypo-chevron-small-down", 0xE760);
        iconMap.put("entypo-chevron-small-up", 0xE763);
        iconMap.put("entypo-chevron-small-right", 0xE762);
        iconMap.put("entypo-chevron-thin-left", 0xE765);
        iconMap.put("entypo-chevron-thin-down", 0xE764);
        iconMap.put("entypo-chevron-thin-up", 0xE767);
        iconMap.put("entypo-chevron-thin-right", 0xE766);
        iconMap.put("entypo-left-thin", 0x2190);
        iconMap.put("entypo-down-thin", 0x2193);
        iconMap.put("entypo-up-thin", 0x2191);
        iconMap.put("entypo-right-thin", 0x2192);
        iconMap.put("entypo-arrow-combo", 0xE74F);
        iconMap.put("entypo-three-dots", 0x23F6);
        iconMap.put("entypo-two-dots", 0x23F5);
        iconMap.put("entypo-dot", 0x23F4);
        iconMap.put("entypo-cc", 0x1F545);
        iconMap.put("entypo-cc-by", 0x1F546);
        iconMap.put("entypo-cc-nc", 0x1F547);
        iconMap.put("entypo-cc-nc-eu", 0x1F548);
        iconMap.put("entypo-cc-nc-jp", 0x1F549);
        iconMap.put("entypo-cc-sa", 0x1F54A);
        iconMap.put("entypo-cc-nd", 0x1F54B);
        iconMap.put("entypo-cc-pd", 0x1F54C);
        iconMap.put("entypo-cc-zero", 0x1F54D);
        iconMap.put("entypo-cc-share", 0x1F54E);
        iconMap.put("entypo-cc-remix", 0x1F54F);
        iconMap.put("entypo-db-logo", 0x1F5F9);
        iconMap.put("entypo-db-shape", 0x1F5FA);

        //Entypo Social
        iconMap.put("esocial-github", 0xF300);
        iconMap.put("esocial-c-github", 0xF301);
        iconMap.put("esocial-flickr", 0xF303);
        iconMap.put("esocial-c-flickr", 0xF304);
        iconMap.put("esocial-vimeo", 0xF306);
        iconMap.put("esocial-c-vimeo", 0xF307);
        iconMap.put("esocial-twitter", 0xF309);
        iconMap.put("esocial-c-twitter", 0xF30A);
        iconMap.put("esocial-facebook", 0xF30C);
        iconMap.put("esocial-c-facebook", 0xF30D);
        iconMap.put("esocial-s-facebook", 0xF30E);
        iconMap.put("esocial-google-plus", 0xF30F);
        iconMap.put("esocial-c-google-plus", 0xF310);
        iconMap.put("esocial-pinterest", 0xF312);
        iconMap.put("esocial-c-pinterest", 0xF313);
        iconMap.put("esocial-tumblr", 0xF315);
        iconMap.put("esocial-c-tumblr", 0xF316);
        iconMap.put("esocial-linkedin", 0xF318);
        iconMap.put("esocial-c-linkedin", 0xF319);
        iconMap.put("esocial-dribble", 0xF31B);
        iconMap.put("esocial-c-dribble", 0xF31C);
        iconMap.put("esocial-stumbleupon", 0xF31E);
        iconMap.put("esocial-c-stumbleupon", 0xF31F);
        iconMap.put("esocial-lastfm", 0xF321);
        iconMap.put("esocial-c-lastfm", 0xF322);
        iconMap.put("esocial-rdio", 0xF324);
        iconMap.put("esocial-c-rdio", 0xF325);
        iconMap.put("esocial-spotify", 0xF327);
        iconMap.put("esocial-c-spotify", 0xF328);
        iconMap.put("esocial-qq", 0xF32A);
        iconMap.put("esocial-instagram", 0xF32D);
        iconMap.put("esocial-dropbox", 0xF330);
        iconMap.put("esocial-evernote", 0xF333);
        iconMap.put("esocial-flattr", 0xF336);
        iconMap.put("esocial-skype", 0xF339);
        iconMap.put("esocial-c-skype", 0xF33A);
        iconMap.put("esocial-renren", 0xF33C);
        iconMap.put("esocial-sina-weibo", 0xF33F);
        iconMap.put("esocial-paypal", 0xF342);
        iconMap.put("esocial-picasa", 0xF345);
        iconMap.put("esocial-soundcloud", 0xF348);
        iconMap.put("esocial-mixi", 0xF34B);
        iconMap.put("esocial-behance", 0xF34E);
        iconMap.put("esocial-google-circles", 0xF351);
        iconMap.put("esocial-vk", 0xF354);
        iconMap.put("esocial-smashing", 0xF357);

        //iconic
        iconMap.put("iconic-search", 0x1F50E);
        iconMap.put("iconic-mail", 0x2709);
        iconMap.put("iconic-heart", 0x2665);
        iconMap.put("iconic-heart-empty", 0x2661);
        iconMap.put("iconic-star", 0x2605);
        iconMap.put("iconic-user", 0x1F464);
        iconMap.put("iconic-video", 0x1F3AC);
        iconMap.put("iconic-picture", 0x1F304);
        iconMap.put("iconic-camera", 0x1F4F7);
        iconMap.put("iconic-ok", 0x2713);
        iconMap.put("iconic-ok-circle", 0x2714);
        iconMap.put("iconic-cancel", 0x2715);
        iconMap.put("iconic-cancel-circle", 0x2716);
        iconMap.put("iconic-plus", 0x2B);
        iconMap.put("iconic-plus-circle", 0x2795);
        iconMap.put("iconic-minus", 0x2D);
        iconMap.put("iconic-minus-circle", 0x2796);
        iconMap.put("iconic-help", 0x2753);
        iconMap.put("iconic-info", 0x2139);
        iconMap.put("iconic-home", 0x2302);
        iconMap.put("iconic-link", 0x1F517);
        iconMap.put("iconic-attach", 0x1F4CE);
        iconMap.put("iconic-lock", 0x1F512);
        iconMap.put("iconic-lock-empty", 0xE708);
        iconMap.put("iconic-lock-open", 0x1F513);
        iconMap.put("iconic-lock-open-empty", 0xE709);
        iconMap.put("iconic-pin", 0x1F4CC);
        iconMap.put("iconic-eye", 0xE70A);
        iconMap.put("iconic-tag", 0xE70C);
        iconMap.put("iconic-tag-empty", 0xE70E);
        iconMap.put("iconic-download", 0x1F4E5);
        iconMap.put("iconic-upload", 0x1F4E4);
        iconMap.put("iconic-download-count", 0xE710);
        iconMap.put("iconic-upload-count", 0xE711);
        iconMap.put("iconic-quote-left", 0x275D);
        iconMap.put("iconic-quote-right", 0x275E);
        iconMap.put("iconic-quote-left-alt", 0x275B);
        iconMap.put("iconic-quote-right-alt", 0x275C);
        iconMap.put("iconic-pencil", 0x270E);
        iconMap.put("iconic-pencil-neg", 0x270F);
        iconMap.put("iconic-pencil-alt", 0x2710);
        iconMap.put("iconic-undo", 0x21B6);
        iconMap.put("iconic-comment", 0xE718);
        iconMap.put("iconic-comment-inv", 0xE719);
        iconMap.put("iconic-comment-alt", 0xE71A);
        iconMap.put("iconic-comment-inv-alt", 0xE71B);
        iconMap.put("iconic-comment-alt2", 0xE71C);
        iconMap.put("iconic-comment-inv-alt2", 0xE71D);
        iconMap.put("iconic-chat", 0xE720);
        iconMap.put("iconic-chat-inv", 0xE721);
        iconMap.put("iconic-location", 0xE724);
        iconMap.put("iconic-location-inv", 0xE725);
        iconMap.put("iconic-location-alt", 0xE726);
        iconMap.put("iconic-compass", 0xE728);
        iconMap.put("iconic-trash", 0xE729);
        iconMap.put("iconic-trash-empty", 0xE72A);
        iconMap.put("iconic-doc", 0xE730);
        iconMap.put("iconic-doc-inv", 0xE731);
        iconMap.put("iconic-doc-alt", 0xE732);
        iconMap.put("iconic-doc-inv-alt", 0xE733);
        iconMap.put("iconic-article", 0xE734);
        iconMap.put("iconic-article-alt", 0xE735);
        iconMap.put("iconic-book-open", 0x1F4D6);
        iconMap.put("iconic-folder", 0x1F4C1);
        iconMap.put("iconic-folder-empty", 0x1F4C2);
        iconMap.put("iconic-box", 0x1F4E6);
        iconMap.put("iconic-rss", 0xE73A);
        iconMap.put("iconic-rss-alt", 0xE73B);
        iconMap.put("iconic-cog", 0x2699);
        iconMap.put("iconic-wrench", 0x1F527);
        iconMap.put("iconic-share", 0xE73C);
        iconMap.put("iconic-calendar", 0x1F4C5);
        iconMap.put("iconic-calendar-inv", 0xE73E);
        iconMap.put("iconic-calendar-alt", 0x1F4C6);
        iconMap.put("iconic-mic", 0x1F3A4);
        iconMap.put("iconic-volume-off", 0x1F507);
        iconMap.put("iconic-volume-up", 0x1F50A);
        iconMap.put("iconic-headphones", 0x1F3A7);
        iconMap.put("iconic-clock", 0x1F554);
        iconMap.put("iconic-lamp", 0x1F4A1);
        iconMap.put("iconic-block", 0x1F6AB);
        iconMap.put("iconic-resize-full", 0xE744);
        iconMap.put("iconic-resize-full-alt", 0xE745);
        iconMap.put("iconic-resize-small", 0xE746);
        iconMap.put("iconic-resize-small-alt", 0xE747);
        iconMap.put("iconic-resize-vertical", 0x2B0C);
        iconMap.put("iconic-resize-horizontal", 0x2B0D);
        iconMap.put("iconic-move", 0xE74A);
        iconMap.put("iconic-popup", 0xE74C);
        iconMap.put("iconic-down", 0x2193);
        iconMap.put("iconic-left", 0x2190);
        iconMap.put("iconic-right", 0x2192);
        iconMap.put("iconic-up", 0x2191);
        iconMap.put("iconic-down-circle", 0xE4A4);
        iconMap.put("iconic-left-circle", 0xE4A1);
        iconMap.put("iconic-right-circle", 0xE4A2);
        iconMap.put("iconic-up-circle", 0xE4A3);
        iconMap.put("iconic-cw", 0x27F3);
        iconMap.put("iconic-loop", 0x1F504);
        iconMap.put("iconic-loop-alt", 0x1F501);
        iconMap.put("iconic-exchange", 0x21C4);
        iconMap.put("iconic-split", 0x2387);
        iconMap.put("iconic-arrow-curved", 0x2935);
        iconMap.put("iconic-play", 0x25B6);
        iconMap.put("iconic-play-circle2", 0xE048);
        iconMap.put("iconic-stop", 0x25AA);
        iconMap.put("iconic-pause", 0x2389);
        iconMap.put("iconic-to-start", 0x23EE);
        iconMap.put("iconic-to-end", 0x23ED);
        iconMap.put("iconic-eject", 0x23CF);
        iconMap.put("iconic-target", 0x1F3AF);
        iconMap.put("iconic-signal", 0x1F4F6);
        iconMap.put("iconic-award", 0x1F3C9);
        iconMap.put("iconic-award-empty", 0xE764);
        iconMap.put("iconic-list", 0xE765);
        iconMap.put("iconic-list-nested", 0xE766);
        iconMap.put("iconic-bat-empty", 0xE772);
        iconMap.put("iconic-bat-half", 0xE774);
        iconMap.put("iconic-bat-full", 0xE774);
        iconMap.put("iconic-bat-charge", 0xE775);
        iconMap.put("iconic-mobile", 0x1F4F1);
        iconMap.put("iconic-cd", 0x1F4BF);
        iconMap.put("iconic-equalizer", 0xE795);
        iconMap.put("iconic-cursor", 0xE796);
        iconMap.put("iconic-aperture", 0xE797);
        iconMap.put("iconic-aperture-alt", 0xE798);
        iconMap.put("iconic-aperture-wheel", 0xE799);
        iconMap.put("iconic-book", 0x1F4D5);
        iconMap.put("iconic-book-alt", 0x1F4D4);
        iconMap.put("iconic-brush", 0xE79A);
        iconMap.put("iconic-brush-alt", 0xE79B);
        iconMap.put("iconic-eyedropper", 0xE79C);
        iconMap.put("iconic-layers", 0xE79D);
        iconMap.put("iconic-layers-alt", 0xE79E);
        iconMap.put("iconic-sun", 0x263C);
        iconMap.put("iconic-sun-inv", 0x2600);
        iconMap.put("iconic-cloud", 0x2601);
        iconMap.put("iconic-rain", 0x26C6);
        iconMap.put("iconic-flash", 0x26A1);
        iconMap.put("iconic-moon", 0x263E);
        iconMap.put("iconic-moon-inv", 0xE7A0);
        iconMap.put("iconic-umbrella", 0x2602);
        iconMap.put("iconic-chart-bar", 0x1F4CA);
        iconMap.put("iconic-chart-pie", 0xE7A2);
        iconMap.put("iconic-chart-pie-alt", 0xE7A3);
        iconMap.put("iconic-key", 0x26BF);
        iconMap.put("iconic-key-inv", 0x1F511);
        iconMap.put("iconic-hash", 0x23);
        iconMap.put("iconic-at", 0x40);
        iconMap.put("iconic-pilcrow", 0xB6);
        iconMap.put("iconic-dial", 0xE7A4);

        //Google material design
        iconMap.put("gmd-3d-rotation", 0xe600 );
        iconMap.put("gmd-accessibility", 0xe601 );
        iconMap.put("gmd-account-balance", 0xe602 );
        iconMap.put("gmd-account-balance-wallet", 0xe603 );
        iconMap.put("gmd-account-box", 0xe604 );
        iconMap.put("gmd-account-child", 0xe605 );
        iconMap.put("gmd-account-circle", 0xe606 );
        iconMap.put("gmd-add-shopping-cart", 0xe607 );
        iconMap.put("gmd-alarm", 0xe608 );
        iconMap.put("gmd-alarm-add", 0xe609 );
        iconMap.put("gmd-alarm-off", 0xe60a );
        iconMap.put("gmd-alarm-on", 0xe60b );
        iconMap.put("gmd-android", 0xe60c );
        iconMap.put("gmd-announcement", 0xe60d );
        iconMap.put("gmd-aspect-ratio", 0xe60e );
        iconMap.put("gmd-assessment", 0xe60f );
        iconMap.put("gmd-assignment", 0xe610 );
        iconMap.put("gmd-assignment-ind", 0xe611 );
        iconMap.put("gmd-assignment-late", 0xe612 );
        iconMap.put("gmd-assignment-return", 0xe613 );
        iconMap.put("gmd-assignment-returned", 0xe614 );
        iconMap.put("gmd-assignment-turned-in", 0xe615 );
        iconMap.put("gmd-autorenew", 0xe616 );
        iconMap.put("gmd-backup", 0xe617 );
        iconMap.put("gmd-book", 0xe618 );
        iconMap.put("gmd-bookmark", 0xe619 );
        iconMap.put("gmd-bookmark-outline", 0xe61a );
        iconMap.put("gmd-bug-report", 0xe61b );
        iconMap.put("gmd-cached", 0xe61c );
        iconMap.put("gmd-class", 0xe61d );
        iconMap.put("gmd-credit-card", 0xe61e );
        iconMap.put("gmd-dashboard", 0xe61f );
        iconMap.put("gmd-delete", 0xe620 );
        iconMap.put("gmd-description", 0xe621 );
        iconMap.put("gmd-dns", 0xe622 );
        iconMap.put("gmd-done", 0xe623 );
        iconMap.put("gmd-done-all", 0xe624 );
        iconMap.put("gmd-event", 0xe625 );
        iconMap.put("gmd-exit-to-app", 0xe626 );
        iconMap.put("gmd-explore", 0xe627 );
        iconMap.put("gmd-extension", 0xe628 );
        iconMap.put("gmd-face-unlock", 0xe629 );
        iconMap.put("gmd-favorite", 0xe62a );
        iconMap.put("gmd-favorite-outline", 0xe62b );
        iconMap.put("gmd-find-in-page", 0xe62c );
        iconMap.put("gmd-find-replace", 0xe62d );
        iconMap.put("gmd-flip-to-back", 0xe62e );
        iconMap.put("gmd-flip-to-front", 0xe62f );
        iconMap.put("gmd-get-app", 0xe630 );
        iconMap.put("gmd-grade", 0xe631 );
        iconMap.put("gmd-group-work", 0xe632 );
        iconMap.put("gmd-help", 0xe633 );
        iconMap.put("gmd-highlight-remove", 0xe634 );
        iconMap.put("gmd-history", 0xe635 );
        iconMap.put("gmd-home", 0xe636 );
        iconMap.put("gmd-https", 0xe637 );
        iconMap.put("gmd-info", 0xe638 );
        iconMap.put("gmd-info-outline", 0xe639 );
        iconMap.put("gmd-input", 0xe63a );
        iconMap.put("gmd-invert-colors", 0xe63b );
        iconMap.put("gmd-label", 0xe63c );
        iconMap.put("gmd-label-outline", 0xe63d );
        iconMap.put("gmd-language", 0xe63e );
        iconMap.put("gmd-launch", 0xe63f );
        iconMap.put("gmd-list", 0xe640 );
        iconMap.put("gmd-lock", 0xe641 );
        iconMap.put("gmd-lock-open", 0xe642 );
        iconMap.put("gmd-lock-outline", 0xe643 );
        iconMap.put("gmd-loyalty", 0xe644 );
        iconMap.put("gmd-markunread-mailbox", 0xe645 );
        iconMap.put("gmd-note-add", 0xe646 );
        iconMap.put("gmd-open-in-browser", 0xe647 );
        iconMap.put("gmd-open-in-new", 0xe648 );
        iconMap.put("gmd-open-with", 0xe649 );
        iconMap.put("gmd-pageview", 0xe64a );
        iconMap.put("gmd-payment", 0xe64b );
        iconMap.put("gmd-perm-camera-m", 0xe64c );
        iconMap.put("gmd-perm-contact-cal", 0xe64d );
        iconMap.put("gmd-perm-data-setting", 0xe64e );
        iconMap.put("gmd-perm-device-info", 0xe64f );
        iconMap.put("gmd-perm-identity", 0xe650 );
        iconMap.put("gmd-perm-media", 0xe651 );
        iconMap.put("gmd-perm-phone-msg", 0xe652 );
        iconMap.put("gmd-perm-scan-wifi", 0xe653 );
        iconMap.put("gmd-picture-in-picture", 0xe654 );
        iconMap.put("gmd-polymer", 0xe655 );
        iconMap.put("gmd-print", 0xe656 );
        iconMap.put("gmd-query-builder", 0xe657 );
        iconMap.put("gmd-question-answer", 0xe658 );
        iconMap.put("gmd-receipt", 0xe659 );
        iconMap.put("gmd-redeem", 0xe65a );
        iconMap.put("gmd-reorder", 0xe65b );
        iconMap.put("gmd-report-problem", 0xe65c );
        iconMap.put("gmd-restore", 0xe65d );
        iconMap.put("gmd-room", 0xe65e );
        iconMap.put("gmd-schedule", 0xe65f );
        iconMap.put("gmd-search", 0xe660 );
        iconMap.put("gmd-settings", 0xe661 );
        iconMap.put("gmd-settings-applications", 0xe662 );
        iconMap.put("gmd-settings-backup-restore", 0xe663 );
        iconMap.put("gmd-settings-bluetooth", 0xe664 );
        iconMap.put("gmd-settings-cell", 0xe665 );
        iconMap.put("gmd-settings-display", 0xe666 );
        iconMap.put("gmd-settings-ethernet", 0xe667 );
        iconMap.put("gmd-settings-input-antenna", 0xe668 );
        iconMap.put("gmd-settings-input-component", 0xe669 );
        iconMap.put("gmd-settings-input-composite", 0xe66a );
        iconMap.put("gmd-settings-input-hdmi", 0xe66b );
        iconMap.put("gmd-settings-input-svideo", 0xe66c );
        iconMap.put("gmd-settings-overscan", 0xe66d );
        iconMap.put("gmd-settings-phone", 0xe66e );
        iconMap.put("gmd-settings-power", 0xe66f );
        iconMap.put("gmd-settings-remote", 0xe670 );
        iconMap.put("gmd-settings-voice", 0xe671 );
        iconMap.put("gmd-shop", 0xe672 );
        iconMap.put("gmd-shop-two", 0xe673 );
        iconMap.put("gmd-shopping-basket", 0xe674 );
        iconMap.put("gmd-shopping-cart", 0xe675 );
        iconMap.put("gmd-speaker-notes", 0xe676 );
        iconMap.put("gmd-spellcheck", 0xe677 );
        iconMap.put("gmd-star-rate", 0xe678 );
        iconMap.put("gmd-stars", 0xe679 );
        iconMap.put("gmd-store", 0xe67a );
        iconMap.put("gmd-subject", 0xe67b );
        iconMap.put("gmd-supervisor-account", 0xe67c );
        iconMap.put("gmd-swap-horiz", 0xe67d );
        iconMap.put("gmd-swap-vert", 0xe67e );
        iconMap.put("gmd-swap-vert-circle", 0xe67f );
        iconMap.put("gmd-system-update-tv", 0xe680 );
        iconMap.put("gmd-tab", 0xe681 );
        iconMap.put("gmd-tab-unselected", 0xe682 );
        iconMap.put("gmd-theaters", 0xe683 );
        iconMap.put("gmd-thumb-down", 0xe684 );
        iconMap.put("gmd-thumb-up", 0xe685 );
        iconMap.put("gmd-thumbs-up-down", 0xe686 );
        iconMap.put("gmd-toc", 0xe687 );
        iconMap.put("gmd-today", 0xe688 );
        iconMap.put("gmd-track-changes", 0xe689 );
        iconMap.put("gmd-translate", 0xe68a );
        iconMap.put("gmd-trending-down", 0xe68b );
        iconMap.put("gmd-trending-neutral", 0xe68c );
        iconMap.put("gmd-trending-up", 0xe68d );
        iconMap.put("gmd-turned-in", 0xe68e );
        iconMap.put("gmd-turned-in-not", 0xe68f );
        iconMap.put("gmd-verified-user", 0xe690 );
        iconMap.put("gmd-view-agenda", 0xe691 );
        iconMap.put("gmd-view-array", 0xe692 );
        iconMap.put("gmd-view-carousel", 0xe693 );
        iconMap.put("gmd-view-column", 0xe694 );
        iconMap.put("gmd-view-day", 0xe695 );
        iconMap.put("gmd-view-headline", 0xe696 );
        iconMap.put("gmd-view-list", 0xe697 );
        iconMap.put("gmd-view-module", 0xe698 );
        iconMap.put("gmd-view-quilt", 0xe699 );
        iconMap.put("gmd-view-stream", 0xe69a );
        iconMap.put("gmd-view-week", 0xe69b );
        iconMap.put("gmd-visibility", 0xe69c );
        iconMap.put("gmd-visibility-off", 0xe69d );
        iconMap.put("gmd-wallet-giftcard", 0xe69e );
        iconMap.put("gmd-wallet-membership", 0xe69f );
        iconMap.put("gmd-wallet-travel", 0xe6a0 );
        iconMap.put("gmd-work", 0xe6a1 );
        iconMap.put("gmd-error", 0xe6a2 );
        iconMap.put("gmd-warning", 0xe6a3 );
        iconMap.put("gmd-album", 0xe6a4 );
        iconMap.put("gmd-av-timer", 0xe6a5 );
        iconMap.put("gmd-closed-caption", 0xe6a6 );
        iconMap.put("gmd-equalizer", 0xe6a7 );
        iconMap.put("gmd-explicit", 0xe6a8 );
        iconMap.put("gmd-fast-forward", 0xe6a9 );
        iconMap.put("gmd-fast-rewind", 0xe6aa );
        iconMap.put("gmd-games", 0xe6ab );
        iconMap.put("gmd-hearing", 0xe6ac );
        iconMap.put("gmd-high-quality", 0xe6ad );
        iconMap.put("gmd-loop", 0xe6ae );
        iconMap.put("gmd-mic", 0xe6af );
        iconMap.put("gmd-mnone", 0xe6b0 );
        iconMap.put("gmd-moff", 0xe6b1 );
        iconMap.put("gmd-movie", 0xe6b2 );
        iconMap.put("gmd-my-library-add", 0xe6b3 );
        iconMap.put("gmd-my-library-books", 0xe6b4 );
        iconMap.put("gmd-my-library-mus", 0xe6b5 );
        iconMap.put("gmd-new-releases", 0xe6b6 );
        iconMap.put("gmd-not-interested", 0xe6b7 );
        iconMap.put("gmd-pause", 0xe6b8 );
        iconMap.put("gmd-pause-circle-fill", 0xe6b9 );
        iconMap.put("gmd-pause-circle-outline", 0xe6ba );
        iconMap.put("gmd-play-arrow", 0xe6bb );
        iconMap.put("gmd-play-circle-fill", 0xe6bc );
        iconMap.put("gmd-play-circle-outline", 0xe6bd );
        iconMap.put("gmd-play-shopping-bag", 0xe6be );
        iconMap.put("gmd-playlist-add", 0xe6bf );
        iconMap.put("gmd-queue", 0xe6c0 );
        iconMap.put("gmd-queue-mus", 0xe6c1 );
        iconMap.put("gmd-radio", 0xe6c2 );
        iconMap.put("gmd-recent-actors", 0xe6c3 );
        iconMap.put("gmd-repeat", 0xe6c4 );
        iconMap.put("gmd-repeat-one", 0xe6c5 );
        iconMap.put("gmd-replay", 0xe6c6 );
        iconMap.put("gmd-shuffle", 0xe6c7 );
        iconMap.put("gmd-skip-next", 0xe6c8 );
        iconMap.put("gmd-skip-previous", 0xe6c9 );
        iconMap.put("gmd-snooze", 0xe6ca );
        iconMap.put("gmd-stop", 0xe6cb );
        iconMap.put("gmd-subtitles", 0xe6cc );
        iconMap.put("gmd-surround-sound", 0xe6cd );
        iconMap.put("gmd-video-collection", 0xe6ce );
        iconMap.put("gmd-videocam", 0xe6cf );
        iconMap.put("gmd-videocam-off", 0xe6d0 );
        iconMap.put("gmd-volume-down", 0xe6d1 );
        iconMap.put("gmd-volume-mute", 0xe6d2 );
        iconMap.put("gmd-volume-off", 0xe6d3 );
        iconMap.put("gmd-volume-up", 0xe6d4 );
        iconMap.put("gmd-web", 0xe6d5 );
        iconMap.put("gmd-business", 0xe6d6 );
        iconMap.put("gmd-call", 0xe6d7 );
        iconMap.put("gmd-call-end", 0xe6d8 );
        iconMap.put("gmd-call-made", 0xe6d9 );
        iconMap.put("gmd-call-merge", 0xe6da );
        iconMap.put("gmd-call-missed", 0xe6db );
        iconMap.put("gmd-call-received", 0xe6dc );
        iconMap.put("gmd-call-split", 0xe6dd );
        iconMap.put("gmd-chat", 0xe6de );
        iconMap.put("gmd-clear-all", 0xe6df );
        iconMap.put("gmd-comment", 0xe6e0 );
        iconMap.put("gmd-contacts", 0xe6e1 );
        iconMap.put("gmd-dialer-sip", 0xe6e2 );
        iconMap.put("gmd-dialpad", 0xe6e3 );
        iconMap.put("gmd-dnd-on", 0xe6e4 );
        iconMap.put("gmd-email", 0xe6e5 );
        iconMap.put("gmd-forum", 0xe6e6 );
        iconMap.put("gmd-import-export", 0xe6e7 );
        iconMap.put("gmd-invert-colors-off", 0xe6e8 );
        iconMap.put("gmd-invert-colors-on", 0xe6e9 );
        iconMap.put("gmd-live-help", 0xe6ea );
        iconMap.put("gmd-location-off", 0xe6eb );
        iconMap.put("gmd-location-on", 0xe6ec );
        iconMap.put("gmd-message", 0xe6ed );
        iconMap.put("gmd-messenger", 0xe6ee );
        iconMap.put("gmd-no-sim", 0xe6ef );
        iconMap.put("gmd-phone", 0xe6f0 );
        iconMap.put("gmd-portable-wifi-off", 0xe6f1 );
        iconMap.put("gmd-quick-contacts-dialer", 0xe6f2 );
        iconMap.put("gmd-quick-contacts-mail", 0xe6f3 );
        iconMap.put("gmd-ring-volume", 0xe6f4 );
        iconMap.put("gmd-stay-current-landscape", 0xe6f5 );
        iconMap.put("gmd-stay-current-portrait", 0xe6f6 );
        iconMap.put("gmd-stay-primary-landscape", 0xe6f7 );
        iconMap.put("gmd-stay-primary-portrait", 0xe6f8 );
        iconMap.put("gmd-swap-calls", 0xe6f9 );
        iconMap.put("gmd-textsms", 0xe6fa );
        iconMap.put("gmd-voicemail", 0xe6fb );
        iconMap.put("gmd-vpn-key", 0xe6fc );
        iconMap.put("gmd-add", 0xe6fd );
        iconMap.put("gmd-add-box", 0xe6fe );
        iconMap.put("gmd-add-circle", 0xe6ff );
        iconMap.put("gmd-add-circle-outline", 0xe700 );
        iconMap.put("gmd-archive", 0xe701 );
        iconMap.put("gmd-backspace", 0xe702 );
        iconMap.put("gmd-block", 0xe703 );
        iconMap.put("gmd-clear", 0xe704 );
        iconMap.put("gmd-content-copy", 0xe705 );
        iconMap.put("gmd-content-cut", 0xe706 );
        iconMap.put("gmd-content-paste", 0xe707 );
        iconMap.put("gmd-create", 0xe708 );
        iconMap.put("gmd-drafts", 0xe709 );
        iconMap.put("gmd-filter-list", 0xe70a );
        iconMap.put("gmd-flag", 0xe70b );
        iconMap.put("gmd-forward", 0xe70c );
        iconMap.put("gmd-gesture", 0xe70d );
        iconMap.put("gmd-inbox", 0xe70e );
        iconMap.put("gmd-link", 0xe70f );
        iconMap.put("gmd-mail", 0xe710 );
        iconMap.put("gmd-markunread", 0xe711 );
        iconMap.put("gmd-redo", 0xe712 );
        iconMap.put("gmd-remove", 0xe713 );
        iconMap.put("gmd-remove-circle", 0xe714 );
        iconMap.put("gmd-remove-circle-outline", 0xe715 );
        iconMap.put("gmd-reply", 0xe716 );
        iconMap.put("gmd-reply-all", 0xe717 );
        iconMap.put("gmd-report", 0xe718 );
        iconMap.put("gmd-save", 0xe719 );
        iconMap.put("gmd-select-all", 0xe71a );
        iconMap.put("gmd-send", 0xe71b );
        iconMap.put("gmd-sort", 0xe71c );
        iconMap.put("gmd-text-format", 0xe71d );
        iconMap.put("gmd-undo", 0xe71e );
        iconMap.put("gmd-access-alarm", 0xe71f );
        iconMap.put("gmd-access-alarms", 0xe720 );
        iconMap.put("gmd-access-time", 0xe721 );
        iconMap.put("gmd-add-alarm", 0xe722 );
        iconMap.put("gmd-airplanemode-off", 0xe723 );
        iconMap.put("gmd-airplanemode-on", 0xe724 );
        iconMap.put("gmd-battery-20", 0xe725 );
        iconMap.put("gmd-battery-30", 0xe726 );
        iconMap.put("gmd-battery-50", 0xe727 );
        iconMap.put("gmd-battery-60", 0xe728 );
        iconMap.put("gmd-battery-80", 0xe729 );
        iconMap.put("gmd-battery-90", 0xe72a );
        iconMap.put("gmd-battery-alert", 0xe72b );
        iconMap.put("gmd-battery-charging-20", 0xe72c );
        iconMap.put("gmd-battery-charging-30", 0xe72d );
        iconMap.put("gmd-battery-charging-50", 0xe72e );
        iconMap.put("gmd-battery-charging-60", 0xe72f );
        iconMap.put("gmd-battery-charging-80", 0xe730 );
        iconMap.put("gmd-battery-charging-90", 0xe731 );
        iconMap.put("gmd-battery-charging-full", 0xe732 );
        iconMap.put("gmd-battery-full", 0xe733 );
        iconMap.put("gmd-battery-std", 0xe734 );
        iconMap.put("gmd-battery-unknown", 0xe735 );
        iconMap.put("gmd-bluetooth", 0xe736 );
        iconMap.put("gmd-bluetooth-connected", 0xe737 );
        iconMap.put("gmd-bluetooth-disabled", 0xe738 );
        iconMap.put("gmd-bluetooth-searching", 0xe739 );
        iconMap.put("gmd-brightness-auto", 0xe73a );
        iconMap.put("gmd-brightness-high", 0xe73b );
        iconMap.put("gmd-brightness-low", 0xe73c );
        iconMap.put("gmd-brightness-medium", 0xe73d );
        iconMap.put("gmd-data-usage", 0xe73e );
        iconMap.put("gmd-developer-mode", 0xe73f );
        iconMap.put("gmd-devices", 0xe740 );
        iconMap.put("gmd-dvr", 0xe741 );
        iconMap.put("gmd-gps-fixed", 0xe742 );
        iconMap.put("gmd-gps-not-fixed", 0xe743 );
        iconMap.put("gmd-gps-off", 0xe744 );
        iconMap.put("gmd-location-disabled", 0xe745 );
        iconMap.put("gmd-location-searching", 0xe746 );
        iconMap.put("gmd-multitrack-audio", 0xe747 );
        iconMap.put("gmd-network-cell", 0xe748 );
        iconMap.put("gmd-network-wifi", 0xe749 );
        iconMap.put("gmd-nfc", 0xe74a );
        iconMap.put("gmd-now-wallpaper", 0xe74b );
        iconMap.put("gmd-now-widgets", 0xe74c );
        iconMap.put("gmd-screen-lock-landscape", 0xe74d );
        iconMap.put("gmd-screen-lock-portrait", 0xe74e );
        iconMap.put("gmd-screen-lock-rotation", 0xe74f );
        iconMap.put("gmd-screen-rotation", 0xe750 );
        iconMap.put("gmd-sd-storage", 0xe751 );
        iconMap.put("gmd-settings-system-daydream", 0xe752 );
        iconMap.put("gmd-signal-cellular-0-bar", 0xe753 );
        iconMap.put("gmd-signal-cellular-1-bar", 0xe754 );
        iconMap.put("gmd-signal-cellular-2-bar", 0xe755 );
        iconMap.put("gmd-signal-cellular-3-bar", 0xe756 );
        iconMap.put("gmd-signal-cellular-4-bar", 0xe757 );
        iconMap.put("gmd-signal-cellular-connected-no-internet-0-bar", 0xe758 );
        iconMap.put("gmd-signal-cellular-connected-no-internet-1-bar", 0xe759 );
        iconMap.put("gmd-signal-cellular-connected-no-internet-2-bar", 0xe75a );
        iconMap.put("gmd-signal-cellular-connected-no-internet-3-bar", 0xe75b );
        iconMap.put("gmd-signal-cellular-connected-no-internet-4-bar", 0xe75c );
        iconMap.put("gmd-signal-cellular-no-sim", 0xe75d );
        iconMap.put("gmd-signal-cellular-null", 0xe75e );
        iconMap.put("gmd-signal-cellular-off", 0xe75f );
        iconMap.put("gmd-signal-wifi-0-bar", 0xe760 );
        iconMap.put("gmd-signal-wifi-1-bar", 0xe761 );
        iconMap.put("gmd-signal-wifi-2-bar", 0xe762 );
        iconMap.put("gmd-signal-wifi-3-bar", 0xe763 );
        iconMap.put("gmd-signal-wifi-4-bar", 0xe764 );
        iconMap.put("gmd-signal-wifi-off", 0xe765 );
        iconMap.put("gmd-signal-wifi-statusbar-1-bar", 0xe766 );
        iconMap.put("gmd-signal-wifi-statusbar-2-bar", 0xe767 );
        iconMap.put("gmd-signal-wifi-statusbar-3-bar", 0xe768 );
        iconMap.put("gmd-signal-wifi-statusbar-4-bar", 0xe769 );
        iconMap.put("gmd-signal-wifi-statusbar-connected-no-internet-1", 0xe76a );
        iconMap.put("gmd-signal-wifi-statusbar-connected-no-internet-2", 0xe76b );
        iconMap.put("gmd-signal-wifi-statusbar-connected-no-internet-3", 0xe76c );
        iconMap.put("gmd-signal-wifi-statusbar-connected-no-internet-4", 0xe76d );
        iconMap.put("gmd-signal-wifi-statusbar-connected-no-internet", 0xe76e );
        iconMap.put("gmd-signal-wifi-statusbar-not-connected", 0xe76f );
        iconMap.put("gmd-signal-wifi-statusbar-null", 0xe770 );
        iconMap.put("gmd-storage", 0xe771 );
        iconMap.put("gmd-usb", 0xe772 );
        iconMap.put("gmd-wifi-lock", 0xe773 );
        iconMap.put("gmd-wifi-tethering", 0xe774 );
        iconMap.put("gmd-attach-file", 0xe775 );
        iconMap.put("gmd-attach-money", 0xe776 );
        iconMap.put("gmd-border-all", 0xe777 );
        iconMap.put("gmd-border-bottom", 0xe778 );
        iconMap.put("gmd-border-clear", 0xe779 );
        iconMap.put("gmd-border-color", 0xe77a );
        iconMap.put("gmd-border-horizontal", 0xe77b );
        iconMap.put("gmd-border-inner", 0xe77c );
        iconMap.put("gmd-border-left", 0xe77d );
        iconMap.put("gmd-border-outer", 0xe77e );
        iconMap.put("gmd-border-right", 0xe77f );
        iconMap.put("gmd-border-style", 0xe780 );
        iconMap.put("gmd-border-top", 0xe781 );
        iconMap.put("gmd-border-vertical", 0xe782 );
        iconMap.put("gmd-format-align-center", 0xe783 );
        iconMap.put("gmd-format-align-justify", 0xe784 );
        iconMap.put("gmd-format-align-left", 0xe785 );
        iconMap.put("gmd-format-align-right", 0xe786 );
        iconMap.put("gmd-format-bold", 0xe787 );
        iconMap.put("gmd-format-clear", 0xe788 );
        iconMap.put("gmd-format-color-fill", 0xe789 );
        iconMap.put("gmd-format-color-reset", 0xe78a );
        iconMap.put("gmd-format-color-text", 0xe78b );
        iconMap.put("gmd-format-indent-decrease", 0xe78c );
        iconMap.put("gmd-format-indent-increase", 0xe78d );
        iconMap.put("gmd-format-ital", 0xe78e );
        iconMap.put("gmd-format-line-spacing", 0xe78f );
        iconMap.put("gmd-format-list-bulleted", 0xe790 );
        iconMap.put("gmd-format-list-numbered", 0xe791 );
        iconMap.put("gmd-format-paint", 0xe792 );
        iconMap.put("gmd-format-quote", 0xe793 );
        iconMap.put("gmd-format-size", 0xe794 );
        iconMap.put("gmd-format-strikethrough", 0xe795 );
        iconMap.put("gmd-format-textdirection-l-to-r", 0xe796 );
        iconMap.put("gmd-format-textdirection-r-to-l", 0xe797 );
        iconMap.put("gmd-format-underline", 0xe798 );
        iconMap.put("gmd-functions", 0xe799 );
        iconMap.put("gmd-insert-chart", 0xe79a );
        iconMap.put("gmd-insert-comment", 0xe79b );
        iconMap.put("gmd-insert-drive-file", 0xe79c );
        iconMap.put("gmd-insert-emoticon", 0xe79d );
        iconMap.put("gmd-insert-invitation", 0xe79e );
        iconMap.put("gmd-insert-link", 0xe79f );
        iconMap.put("gmd-insert-photo", 0xe7a0 );
        iconMap.put("gmd-merge-type", 0xe7a1 );
        iconMap.put("gmd-mode-comment", 0xe7a2 );
        iconMap.put("gmd-mode-edit", 0xe7a3 );
        iconMap.put("gmd-publish", 0xe7a4 );
        iconMap.put("gmd-vertical-align-bottom", 0xe7a5 );
        iconMap.put("gmd-vertical-align-center", 0xe7a6 );
        iconMap.put("gmd-vertical-align-top", 0xe7a7 );
        iconMap.put("gmd-wrap-text", 0xe7a8 );
        iconMap.put("gmd-attachment", 0xe7a9 );
        iconMap.put("gmd-cloud", 0xe7aa );
        iconMap.put("gmd-cloud-circle", 0xe7ab );
        iconMap.put("gmd-cloud-done", 0xe7ac );
        iconMap.put("gmd-cloud-download", 0xe7ad );
        iconMap.put("gmd-cloud-off", 0xe7ae );
        iconMap.put("gmd-cloud-queue", 0xe7af );
        iconMap.put("gmd-cloud-upload", 0xe7b0 );
        iconMap.put("gmd-file-download", 0xe7b1 );
        iconMap.put("gmd-file-upload", 0xe7b2 );
        iconMap.put("gmd-folder", 0xe7b3 );
        iconMap.put("gmd-folder-open", 0xe7b4 );
        iconMap.put("gmd-folder-shared", 0xe7b5 );
        iconMap.put("gmd-cast", 0xe7b6 );
        iconMap.put("gmd-cast-connected", 0xe7b7 );
        iconMap.put("gmd-computer", 0xe7b8 );
        iconMap.put("gmd-desktop-mac", 0xe7b9 );
        iconMap.put("gmd-desktop-windows", 0xe7ba );
        iconMap.put("gmd-dock", 0xe7bb );
        iconMap.put("gmd-gamepad", 0xe7bc );
        iconMap.put("gmd-headset", 0xe7bd );
        iconMap.put("gmd-headset-m", 0xe7be );
        iconMap.put("gmd-keyboard", 0xe7bf );
        iconMap.put("gmd-keyboard-alt", 0xe7c0 );
        iconMap.put("gmd-keyboard-arrow-down", 0xe7c1 );
        iconMap.put("gmd-keyboard-arrow-left", 0xe7c2 );
        iconMap.put("gmd-keyboard-arrow-right", 0xe7c3 );
        iconMap.put("gmd-keyboard-arrow-up", 0xe7c4 );
        iconMap.put("gmd-keyboard-backspace", 0xe7c5 );
        iconMap.put("gmd-keyboard-capslock", 0xe7c6 );
        iconMap.put("gmd-keyboard-control", 0xe7c7 );
        iconMap.put("gmd-keyboard-hide", 0xe7c8 );
        iconMap.put("gmd-keyboard-return", 0xe7c9 );
        iconMap.put("gmd-keyboard-tab", 0xe7ca );
        iconMap.put("gmd-keyboard-voice", 0xe7cb );
        iconMap.put("gmd-laptop", 0xe7cc );
        iconMap.put("gmd-laptop-chromebook", 0xe7cd );
        iconMap.put("gmd-laptop-mac", 0xe7ce );
        iconMap.put("gmd-laptop-windows", 0xe7cf );
        iconMap.put("gmd-memory", 0xe7d0 );
        iconMap.put("gmd-mouse", 0xe7d1 );
        iconMap.put("gmd-phone-android", 0xe7d2 );
        iconMap.put("gmd-phone-iphone", 0xe7d3 );
        iconMap.put("gmd-phonelink", 0xe7d4 );
        iconMap.put("gmd-phonelink-off", 0xe7d5 );
        iconMap.put("gmd-security", 0xe7d6 );
        iconMap.put("gmd-sim-card", 0xe7d7 );
        iconMap.put("gmd-smartphone", 0xe7d8 );
        iconMap.put("gmd-speaker", 0xe7d9 );
        iconMap.put("gmd-tablet", 0xe7da );
        iconMap.put("gmd-tablet-android", 0xe7db );
        iconMap.put("gmd-tablet-mac", 0xe7dc );
        iconMap.put("gmd-tv", 0xe7dd );
        iconMap.put("gmd-watch", 0xe7de );
        iconMap.put("gmd-add-to-photos", 0xe7df );
        iconMap.put("gmd-adjust", 0xe7e0 );
        iconMap.put("gmd-assistant-photo", 0xe7e1 );
        iconMap.put("gmd-audiotrack", 0xe7e2 );
        iconMap.put("gmd-blur-circular", 0xe7e3 );
        iconMap.put("gmd-blur-linear", 0xe7e4 );
        iconMap.put("gmd-blur-off", 0xe7e5 );
        iconMap.put("gmd-blur-on", 0xe7e6 );
        iconMap.put("gmd-brightness-1", 0xe7e7 );
        iconMap.put("gmd-brightness-2", 0xe7e8 );
        iconMap.put("gmd-brightness-3", 0xe7e9 );
        iconMap.put("gmd-brightness-4", 0xe7ea );
        iconMap.put("gmd-brightness-5", 0xe7eb );
        iconMap.put("gmd-brightness-6", 0xe7ec );
        iconMap.put("gmd-brightness-7", 0xe7ed );
        iconMap.put("gmd-brush", 0xe7ee );
        iconMap.put("gmd-camera", 0xe7ef );
        iconMap.put("gmd-camera-alt", 0xe7f0 );
        iconMap.put("gmd-camera-front", 0xe7f1 );
        iconMap.put("gmd-camera-rear", 0xe7f2 );
        iconMap.put("gmd-camera-roll", 0xe7f3 );
        iconMap.put("gmd-center-focus-strong", 0xe7f4 );
        iconMap.put("gmd-center-focus-weak", 0xe7f5 );
        iconMap.put("gmd-collections", 0xe7f6 );
        iconMap.put("gmd-color-lens", 0xe7f7 );
        iconMap.put("gmd-colorize", 0xe7f8 );
        iconMap.put("gmd-compare", 0xe7f9 );
        iconMap.put("gmd-control-point", 0xe7fa );
        iconMap.put("gmd-control-point-duplicate", 0xe7fb );
        iconMap.put("gmd-crop-3-2", 0xe7fc );
        iconMap.put("gmd-crop-5-4", 0xe7fd );
        iconMap.put("gmd-crop-7-5", 0xe7fe );
        iconMap.put("gmd-crop-16-9", 0xe7ff );
        iconMap.put("gmd-crop", 0xe800 );
        iconMap.put("gmd-crop-din", 0xe801 );
        iconMap.put("gmd-crop-free", 0xe802 );
        iconMap.put("gmd-crop-landscape", 0xe803 );
        iconMap.put("gmd-crop-original", 0xe804 );
        iconMap.put("gmd-crop-portrait", 0xe805 );
        iconMap.put("gmd-crop-square", 0xe806 );
        iconMap.put("gmd-dehaze", 0xe807 );
        iconMap.put("gmd-details", 0xe808 );
        iconMap.put("gmd-edit", 0xe809 );
        iconMap.put("gmd-exposure", 0xe80a );
        iconMap.put("gmd-exposure-minus-1", 0xe80b );
        iconMap.put("gmd-exposure-minus-2", 0xe80c );
        iconMap.put("gmd-exposure-plus-1", 0xe80d );
        iconMap.put("gmd-exposure-plus-2", 0xe80e );
        iconMap.put("gmd-exposure-zero", 0xe80f );
        iconMap.put("gmd-filter-1", 0xe810 );
        iconMap.put("gmd-filter-2", 0xe811 );
        iconMap.put("gmd-filter-3", 0xe812 );
        iconMap.put("gmd-filter-4", 0xe813 );
        iconMap.put("gmd-filter-5", 0xe814 );
        iconMap.put("gmd-filter-6", 0xe815 );
        iconMap.put("gmd-filter-7", 0xe816 );
        iconMap.put("gmd-filter-8", 0xe817 );
        iconMap.put("gmd-filter-9", 0xe818 );
        iconMap.put("gmd-filter-9-plus", 0xe819 );
        iconMap.put("gmd-filter", 0xe81a );
        iconMap.put("gmd-filter-b-and-w", 0xe81b );
        iconMap.put("gmd-filter-center-focus", 0xe81c );
        iconMap.put("gmd-filter-drama", 0xe81d );
        iconMap.put("gmd-filter-frames", 0xe81e );
        iconMap.put("gmd-filter-hdr", 0xe81f );
        iconMap.put("gmd-filter-none", 0xe820 );
        iconMap.put("gmd-filter-tilt-shift", 0xe821 );
        iconMap.put("gmd-filter-vintage", 0xe822 );
        iconMap.put("gmd-flare", 0xe823 );
        iconMap.put("gmd-flash-auto", 0xe824 );
        iconMap.put("gmd-flash-off", 0xe825 );
        iconMap.put("gmd-flash-on", 0xe826 );
        iconMap.put("gmd-flip", 0xe827 );
        iconMap.put("gmd-gradient", 0xe828 );
        iconMap.put("gmd-grain", 0xe829 );
        iconMap.put("gmd-grid-off", 0xe82a );
        iconMap.put("gmd-grid-on", 0xe82b );
        iconMap.put("gmd-hdr-off", 0xe82c );
        iconMap.put("gmd-hdr-on", 0xe82d );
        iconMap.put("gmd-hdr-strong", 0xe82e );
        iconMap.put("gmd-hdr-weak", 0xe82f );
        iconMap.put("gmd-healing", 0xe830 );
        iconMap.put("gmd-image", 0xe831 );
        iconMap.put("gmd-image-aspect-ratio", 0xe832 );
        iconMap.put("gmd-iso", 0xe833 );
        iconMap.put("gmd-landscape", 0xe834 );
        iconMap.put("gmd-leak-add", 0xe835 );
        iconMap.put("gmd-leak-remove", 0xe836 );
        iconMap.put("gmd-lens", 0xe837 );
        iconMap.put("gmd-looks-3", 0xe838 );
        iconMap.put("gmd-looks-4", 0xe839 );
        iconMap.put("gmd-looks-5", 0xe83a );
        iconMap.put("gmd-looks-6", 0xe83b );
        iconMap.put("gmd-looks", 0xe83c );
        iconMap.put("gmd-looks-one", 0xe83d );
        iconMap.put("gmd-looks-two", 0xe83e );
        iconMap.put("gmd-loupe", 0xe83f );
        iconMap.put("gmd-movie-creation", 0xe840 );
        iconMap.put("gmd-nature", 0xe841 );
        iconMap.put("gmd-nature-people", 0xe842 );
        iconMap.put("gmd-navigate-before", 0xe843 );
        iconMap.put("gmd-navigate-next", 0xe844 );
        iconMap.put("gmd-palette", 0xe845 );
        iconMap.put("gmd-panorama", 0xe846 );
        iconMap.put("gmd-panorama-fisheye", 0xe847 );
        iconMap.put("gmd-panorama-horizontal", 0xe848 );
        iconMap.put("gmd-panorama-vertical", 0xe849 );
        iconMap.put("gmd-panorama-wide-angle", 0xe84a );
        iconMap.put("gmd-photo", 0xe84b );
        iconMap.put("gmd-photo-album", 0xe84c );
        iconMap.put("gmd-photo-camera", 0xe84d );
        iconMap.put("gmd-photo-library", 0xe84e );
        iconMap.put("gmd-portrait", 0xe84f );
        iconMap.put("gmd-remove-red-eye", 0xe850 );
        iconMap.put("gmd-rotate-left", 0xe851 );
        iconMap.put("gmd-rotate-right", 0xe852 );
        iconMap.put("gmd-slideshow", 0xe853 );
        iconMap.put("gmd-straighten", 0xe854 );
        iconMap.put("gmd-style", 0xe855 );
        iconMap.put("gmd-switch-camera", 0xe856 );
        iconMap.put("gmd-switch-video", 0xe857 );
        iconMap.put("gmd-tag-faces", 0xe858 );
        iconMap.put("gmd-texture", 0xe859 );
        iconMap.put("gmd-timelapse", 0xe85a );
        iconMap.put("gmd-timer-3", 0xe85b );
        iconMap.put("gmd-timer-10", 0xe85c );
        iconMap.put("gmd-timer", 0xe85d );
        iconMap.put("gmd-timer-auto", 0xe85e );
        iconMap.put("gmd-timer-off", 0xe85f );
        iconMap.put("gmd-tonality", 0xe860 );
        iconMap.put("gmd-transform", 0xe861 );
        iconMap.put("gmd-tune", 0xe862 );
        iconMap.put("gmd-wb-auto", 0xe863 );
        iconMap.put("gmd-wb-cloudy", 0xe864 );
        iconMap.put("gmd-wb-incandescent", 0xe865 );
        iconMap.put("gmd-wb-irradescent", 0xe866 );
        iconMap.put("gmd-wb-sunny", 0xe867 );
        iconMap.put("gmd-beenhere", 0xe868 );
        iconMap.put("gmd-directions", 0xe869 );
        iconMap.put("gmd-directions-bike", 0xe86a );
        iconMap.put("gmd-directions-bus", 0xe86b );
        iconMap.put("gmd-directions-car", 0xe86c );
        iconMap.put("gmd-directions-ferry", 0xe86d );
        iconMap.put("gmd-directions-subway", 0xe86e );
        iconMap.put("gmd-directions-train", 0xe86f );
        iconMap.put("gmd-directions-transit", 0xe870 );
        iconMap.put("gmd-directions-walk", 0xe871 );
        iconMap.put("gmd-flight", 0xe872 );
        iconMap.put("gmd-hotel", 0xe873 );
        iconMap.put("gmd-layers", 0xe874 );
        iconMap.put("gmd-layers-clear", 0xe875 );
        iconMap.put("gmd-local-airport", 0xe876 );
        iconMap.put("gmd-local-atm", 0xe877 );
        iconMap.put("gmd-local-attraction", 0xe878 );
        iconMap.put("gmd-local-bar", 0xe879 );
        iconMap.put("gmd-local-cafe", 0xe87a );
        iconMap.put("gmd-local-car-wash", 0xe87b );
        iconMap.put("gmd-local-convenience-store", 0xe87c );
        iconMap.put("gmd-local-drink", 0xe87d );
        iconMap.put("gmd-local-florist", 0xe87e );
        iconMap.put("gmd-local-gas-station", 0xe87f );
        iconMap.put("gmd-local-grocery-store", 0xe880 );
        iconMap.put("gmd-local-hospital", 0xe881 );
        iconMap.put("gmd-local-hotel", 0xe882 );
        iconMap.put("gmd-local-laundry-service", 0xe883 );
        iconMap.put("gmd-local-library", 0xe884 );
        iconMap.put("gmd-local-mall", 0xe885 );
        iconMap.put("gmd-local-movies", 0xe886 );
        iconMap.put("gmd-local-offer", 0xe887 );
        iconMap.put("gmd-local-parking", 0xe888 );
        iconMap.put("gmd-local-pharmacy", 0xe889 );
        iconMap.put("gmd-local-phone", 0xe88a );
        iconMap.put("gmd-local-pizza", 0xe88b );
        iconMap.put("gmd-local-play", 0xe88c );
        iconMap.put("gmd-local-post-office", 0xe88d );
        iconMap.put("gmd-local-print-shop", 0xe88e );
        iconMap.put("gmd-local-restaurant", 0xe88f );
        iconMap.put("gmd-local-see", 0xe890 );
        iconMap.put("gmd-local-shipping", 0xe891 );
        iconMap.put("gmd-local-taxi", 0xe892 );
        iconMap.put("gmd-location-history", 0xe893 );
        iconMap.put("gmd-map", 0xe894 );
        iconMap.put("gmd-my-location", 0xe895 );
        iconMap.put("gmd-navigation", 0xe896 );
        iconMap.put("gmd-pin-drop", 0xe897 );
        iconMap.put("gmd-place", 0xe898 );
        iconMap.put("gmd-rate-review", 0xe899 );
        iconMap.put("gmd-restaurant-menu", 0xe89a );
        iconMap.put("gmd-satellite", 0xe89b );
        iconMap.put("gmd-store-mall-directory", 0xe89c );
        iconMap.put("gmd-terrain", 0xe89d );
        iconMap.put("gmd-traff", 0xe89e );
        iconMap.put("gmd-apps", 0xe89f );
        iconMap.put("gmd-arrow-back", 0xe8a0 );
        iconMap.put("gmd-arrow-drop-down", 0xe8a1 );
        iconMap.put("gmd-arrow-drop-down-circle", 0xe8a2 );
        iconMap.put("gmd-arrow-drop-up", 0xe8a3 );
        iconMap.put("gmd-arrow-forward", 0xe8a4 );
        iconMap.put("gmd-cancel", 0xe8a5 );
        iconMap.put("gmd-check", 0xe8a6 );
        iconMap.put("gmd-chevron-left", 0xe8a7 );
        iconMap.put("gmd-chevron-right", 0xe8a8 );
        iconMap.put("gmd-close", 0xe8a9 );
        iconMap.put("gmd-expand-less", 0xe8aa );
        iconMap.put("gmd-expand-more", 0xe8ab );
        iconMap.put("gmd-fullscreen", 0xe8ac );
        iconMap.put("gmd-fullscreen-exit", 0xe8ad );
        iconMap.put("gmd-menu", 0xe8ae );
        iconMap.put("gmd-more-horiz", 0xe8af );
        iconMap.put("gmd-more-vert", 0xe8b0 );
        iconMap.put("gmd-refresh", 0xe8b1 );
        iconMap.put("gmd-unfold-less", 0xe8b2 );
        iconMap.put("gmd-unfold-more", 0xe8b3 );
        iconMap.put("gmd-adb", 0xe8b4 );
        iconMap.put("gmd-bluetooth-audio", 0xe8b5 );
        iconMap.put("gmd-disc-full", 0xe8b6 );
        iconMap.put("gmd-dnd-forwardslash", 0xe8b7 );
        iconMap.put("gmd-do-not-disturb", 0xe8b8 );
        iconMap.put("gmd-drive-eta", 0xe8b9 );
        iconMap.put("gmd-event-available", 0xe8ba );
        iconMap.put("gmd-event-busy", 0xe8bb );
        iconMap.put("gmd-event-note", 0xe8bc );
        iconMap.put("gmd-folder-special", 0xe8bd );
        iconMap.put("gmd-mms", 0xe8be );
        iconMap.put("gmd-more", 0xe8bf );
        iconMap.put("gmd-network-locked", 0xe8c0 );
        iconMap.put("gmd-phone-bluetooth-speaker", 0xe8c1 );
        iconMap.put("gmd-phone-forwarded", 0xe8c2 );
        iconMap.put("gmd-phone-in-talk", 0xe8c3 );
        iconMap.put("gmd-phone-locked", 0xe8c4 );
        iconMap.put("gmd-phone-missed", 0xe8c5 );
        iconMap.put("gmd-phone-paused", 0xe8c6 );
        iconMap.put("gmd-play-download", 0xe8c7 );
        iconMap.put("gmd-play-install", 0xe8c8 );
        iconMap.put("gmd-sd-card", 0xe8c9 );
        iconMap.put("gmd-sim-card-alert", 0xe8ca );
        iconMap.put("gmd-sms", 0xe8cb );
        iconMap.put("gmd-sms-failed", 0xe8cc );
        iconMap.put("gmd-sync", 0xe8cd );
        iconMap.put("gmd-sync-disabled", 0xe8ce );
        iconMap.put("gmd-sync-problem", 0xe8cf );
        iconMap.put("gmd-system-update", 0xe8d0 );
        iconMap.put("gmd-tap-and-play", 0xe8d1 );
        iconMap.put("gmd-time-to-leave", 0xe8d2 );
        iconMap.put("gmd-vibration", 0xe8d3 );
        iconMap.put("gmd-voice-chat", 0xe8d4 );
        iconMap.put("gmd-vpn-lock", 0xe8d5 );
        iconMap.put("gmd-cake", 0xe8d6 );
        iconMap.put("gmd-domain", 0xe8d7 );
        iconMap.put("gmd-group", 0xe8d8 );
        iconMap.put("gmd-group-add", 0xe8d9 );
        iconMap.put("gmd-location-city", 0xe8da );
        iconMap.put("gmd-mood", 0xe8db );
        iconMap.put("gmd-notifications", 0xe8dc );
        iconMap.put("gmd-notifications-none", 0xe8dd );
        iconMap.put("gmd-notifications-off", 0xe8de );
        iconMap.put("gmd-notifications-on", 0xe8df );
        iconMap.put("gmd-notifications-paused", 0xe8e0 );
        iconMap.put("gmd-pages", 0xe8e1 );
        iconMap.put("gmd-party-mode", 0xe8e2 );
        iconMap.put("gmd-people", 0xe8e3 );
        iconMap.put("gmd-people-outline", 0xe8e4 );
        iconMap.put("gmd-person", 0xe8e5 );
        iconMap.put("gmd-person-add", 0xe8e6 );
        iconMap.put("gmd-person-outline", 0xe8e7 );
        iconMap.put("gmd-plus-one", 0xe8e8 );
        iconMap.put("gmd-poll", 0xe8e9 );
        iconMap.put("gmd-publ", 0xe8ea );
        iconMap.put("gmd-school", 0xe8eb );
        iconMap.put("gmd-share", 0xe8ec );
        iconMap.put("gmd-whatshot", 0xe8ed );
        iconMap.put("gmd-check-box", 0xe8ee );
        iconMap.put("gmd-check-box-outline-blank", 0xe8ef );
        iconMap.put("gmd-radio-button-off", 0xe8f0 );
        iconMap.put("gmd-radio-button-on", 0xe8f1 );
        iconMap.put("gmd-star", 0xe8f2 );
        iconMap.put("gmd-star-half", 0xe8f3 );
        iconMap.put("gmd-star-outline", 0xe8f4 );

        //meteocons
        iconMap.put("meteo-sunrise", 0xe600 );
        iconMap.put("meteo-sun", 0xe601 );
        iconMap.put("meteo-moon", 0xe602 );
        iconMap.put("meteo-sun2", 0xe603 );
        iconMap.put("meteo-windy", 0xe604 );
        iconMap.put("meteo-wind", 0xe605 );
        iconMap.put("meteo-snowflake", 0xe606 );
        iconMap.put("meteo-cloudy", 0xe607 );
        iconMap.put("meteo-cloud", 0xe608 );
        iconMap.put("meteo-weather", 0xe609 );
        iconMap.put("meteo-weather2", 0xe60a );
        iconMap.put("meteo-weather3", 0xe60b );
        iconMap.put("meteo-lines", 0xe60c );
        iconMap.put("meteo-cloud2", 0xe60d );
        iconMap.put("meteo-lightning", 0xe60e );
        iconMap.put("meteo-lightning2", 0xe60f );
        iconMap.put("meteo-rainy", 0xe610 );
        iconMap.put("meteo-rainy2", 0xe611 );
        iconMap.put("meteo-windy2", 0xe612 );
        iconMap.put("meteo-windy3", 0xe613 );
        iconMap.put("meteo-snowy", 0xe614 );
        iconMap.put("meteo-snowy2", 0xe615 );
        iconMap.put("meteo-snowy3", 0xe616 );
        iconMap.put("meteo-weather4", 0xe617 );
        iconMap.put("meteo-cloudy2", 0xe618 );
        iconMap.put("meteo-cloud3", 0xe619 );
        iconMap.put("meteo-lightning3", 0xe61a );
        iconMap.put("meteo-sun3", 0xe61b );
        iconMap.put("meteo-moon2", 0xe61c );
        iconMap.put("meteo-cloudy3", 0xe61d );
        iconMap.put("meteo-cloud4", 0xe61e );
        iconMap.put("meteo-cloud5", 0xe61f );
        iconMap.put("meteo-lightning4", 0xe620 );
        iconMap.put("meteo-rainy3", 0xe621 );
        iconMap.put("meteo-rainy4", 0xe622 );
        iconMap.put("meteo-windy4", 0xe623 );
        iconMap.put("meteo-windy5", 0xe624 );
        iconMap.put("meteo-snowy4", 0xe625 );
        iconMap.put("meteo-snowy5", 0xe626 );
        iconMap.put("meteo-weather5", 0xe627 );
        iconMap.put("meteo-cloudy4", 0xe628 );
        iconMap.put("meteo-lightning5", 0xe629 );
        iconMap.put("meteo-thermometer", 0xe62a );
        iconMap.put("meteo-compass", 0xe62b );
        iconMap.put("meteo-none", 0xe62c );
        iconMap.put("meteo-Celsius", 0xe62d );
        iconMap.put("meteo-Fahrenheit", 0xe62e );


    }

    public static Map<String, Integer> getIconMap()
    {
        return iconMap;
    }


    public static TypefaceManager.IconicTypeface getIconicTypeface(String icon)
    {
        if(icon.startsWith("fa"))
            return TypefaceManager.IconicTypeface.FONT_AWESOME;
        else if(icon.startsWith("entypo"))
            return TypefaceManager.IconicTypeface.ENTYPO;
        else if(icon.startsWith("esocial"))
            return TypefaceManager.IconicTypeface.ENTYPO_SOCIAL;
        else if(icon.startsWith("iconic"))
            return TypefaceManager.IconicTypeface.ICONIC;
        else if(icon.startsWith("gmd"))
            return TypefaceManager.IconicTypeface.GOOGLE_MATERIAL_DESIGN;
        else if(icon.startsWith("meteo"))
            return TypefaceManager.IconicTypeface.METEOCON;
        else return null;
    }

    public static int getIconUtfValue(String icon) {
        return iconMap.get(icon);
    }
}
