package com.thedazzler.droidicon.typeface;

import java.util.HashMap;
import java.util.Map;

/**
 * Author: Zhibo Wei (zweicmu@gmail.com), 2/3/15.
 */
public class IconicTypefaceHolder extends TypefaceHolder {

    private final Map<String, Integer> iconicIconMap = new HashMap<String, Integer>();

    IconicTypefaceHolder(String prefix, int resourceId) {
        super(prefix, resourceId);
        initIconMap();
        setIconMap(iconicIconMap);
    }

    private void initIconMap() {
        iconicIconMap.put("iconic-search", 0x1F50E);
        iconicIconMap.put("iconic-mail", 0x2709);
        iconicIconMap.put("iconic-heart", 0x2665);
        iconicIconMap.put("iconic-heart-empty", 0x2661);
        iconicIconMap.put("iconic-star", 0x2605);
        iconicIconMap.put("iconic-user", 0x1F464);
        iconicIconMap.put("iconic-video", 0x1F3AC);
        iconicIconMap.put("iconic-picture", 0x1F304);
        iconicIconMap.put("iconic-camera", 0x1F4F7);
        iconicIconMap.put("iconic-ok", 0x2713);
        iconicIconMap.put("iconic-ok-circle", 0x2714);
        iconicIconMap.put("iconic-cancel", 0x2715);
        iconicIconMap.put("iconic-cancel-circle", 0x2716);
        iconicIconMap.put("iconic-plus", 0x2B);
        iconicIconMap.put("iconic-plus-circle", 0x2795);
        iconicIconMap.put("iconic-minus", 0x2D);
        iconicIconMap.put("iconic-minus-circle", 0x2796);
        iconicIconMap.put("iconic-help", 0x2753);
        iconicIconMap.put("iconic-info", 0x2139);
        iconicIconMap.put("iconic-home", 0x2302);
        iconicIconMap.put("iconic-link", 0x1F517);
        iconicIconMap.put("iconic-attach", 0x1F4CE);
        iconicIconMap.put("iconic-lock", 0x1F512);
        iconicIconMap.put("iconic-lock-empty", 0xE708);
        iconicIconMap.put("iconic-lock-open", 0x1F513);
        iconicIconMap.put("iconic-lock-open-empty", 0xE709);
        iconicIconMap.put("iconic-pin", 0x1F4CC);
        iconicIconMap.put("iconic-eye", 0xE70A);
        iconicIconMap.put("iconic-tag", 0xE70C);
        iconicIconMap.put("iconic-tag-empty", 0xE70E);
        iconicIconMap.put("iconic-download", 0x1F4E5);
        iconicIconMap.put("iconic-upload", 0x1F4E4);
        iconicIconMap.put("iconic-download-count", 0xE710);
        iconicIconMap.put("iconic-upload-count", 0xE711);
        iconicIconMap.put("iconic-quote-left", 0x275D);
        iconicIconMap.put("iconic-quote-right", 0x275E);
        iconicIconMap.put("iconic-quote-left-alt", 0x275B);
        iconicIconMap.put("iconic-quote-right-alt", 0x275C);
        iconicIconMap.put("iconic-pencil", 0x270E);
        iconicIconMap.put("iconic-pencil-neg", 0x270F);
        iconicIconMap.put("iconic-pencil-alt", 0x2710);
        iconicIconMap.put("iconic-undo", 0x21B6);
        iconicIconMap.put("iconic-comment", 0xE718);
        iconicIconMap.put("iconic-comment-inv", 0xE719);
        iconicIconMap.put("iconic-comment-alt", 0xE71A);
        iconicIconMap.put("iconic-comment-inv-alt", 0xE71B);
        iconicIconMap.put("iconic-comment-alt2", 0xE71C);
        iconicIconMap.put("iconic-comment-inv-alt2", 0xE71D);
        iconicIconMap.put("iconic-chat", 0xE720);
        iconicIconMap.put("iconic-chat-inv", 0xE721);
        iconicIconMap.put("iconic-location", 0xE724);
        iconicIconMap.put("iconic-location-inv", 0xE725);
        iconicIconMap.put("iconic-location-alt", 0xE726);
        iconicIconMap.put("iconic-compass", 0xE728);
        iconicIconMap.put("iconic-trash", 0xE729);
        iconicIconMap.put("iconic-trash-empty", 0xE72A);
        iconicIconMap.put("iconic-doc", 0xE730);
        iconicIconMap.put("iconic-doc-inv", 0xE731);
        iconicIconMap.put("iconic-doc-alt", 0xE732);
        iconicIconMap.put("iconic-doc-inv-alt", 0xE733);
        iconicIconMap.put("iconic-article", 0xE734);
        iconicIconMap.put("iconic-article-alt", 0xE735);
        iconicIconMap.put("iconic-book-open", 0x1F4D6);
        iconicIconMap.put("iconic-folder", 0x1F4C1);
        iconicIconMap.put("iconic-folder-empty", 0x1F4C2);
        iconicIconMap.put("iconic-box", 0x1F4E6);
        iconicIconMap.put("iconic-rss", 0xE73A);
        iconicIconMap.put("iconic-rss-alt", 0xE73B);
        iconicIconMap.put("iconic-cog", 0x2699);
        iconicIconMap.put("iconic-wrench", 0x1F527);
        iconicIconMap.put("iconic-share", 0xE73C);
        iconicIconMap.put("iconic-calendar", 0x1F4C5);
        iconicIconMap.put("iconic-calendar-inv", 0xE73E);
        iconicIconMap.put("iconic-calendar-alt", 0x1F4C6);
        iconicIconMap.put("iconic-mic", 0x1F3A4);
        iconicIconMap.put("iconic-volume-off", 0x1F507);
        iconicIconMap.put("iconic-volume-up", 0x1F50A);
        iconicIconMap.put("iconic-headphones", 0x1F3A7);
        iconicIconMap.put("iconic-clock", 0x1F554);
        iconicIconMap.put("iconic-lamp", 0x1F4A1);
        iconicIconMap.put("iconic-block", 0x1F6AB);
        iconicIconMap.put("iconic-resize-full", 0xE744);
        iconicIconMap.put("iconic-resize-full-alt", 0xE745);
        iconicIconMap.put("iconic-resize-small", 0xE746);
        iconicIconMap.put("iconic-resize-small-alt", 0xE747);
        iconicIconMap.put("iconic-resize-vertical", 0x2B0C);
        iconicIconMap.put("iconic-resize-horizontal", 0x2B0D);
        iconicIconMap.put("iconic-move", 0xE74A);
        iconicIconMap.put("iconic-popup", 0xE74C);
        iconicIconMap.put("iconic-down", 0x2193);
        iconicIconMap.put("iconic-left", 0x2190);
        iconicIconMap.put("iconic-right", 0x2192);
        iconicIconMap.put("iconic-up", 0x2191);
        iconicIconMap.put("iconic-down-circle", 0xE4A4);
        iconicIconMap.put("iconic-left-circle", 0xE4A1);
        iconicIconMap.put("iconic-right-circle", 0xE4A2);
        iconicIconMap.put("iconic-up-circle", 0xE4A3);
        iconicIconMap.put("iconic-cw", 0x27F3);
        iconicIconMap.put("iconic-loop", 0x1F504);
        iconicIconMap.put("iconic-loop-alt", 0x1F501);
        iconicIconMap.put("iconic-exchange", 0x21C4);
        iconicIconMap.put("iconic-split", 0x2387);
        iconicIconMap.put("iconic-arrow-curved", 0x2935);
        iconicIconMap.put("iconic-play", 0x25B6);
        iconicIconMap.put("iconic-play-circle2", 0xE048);
        iconicIconMap.put("iconic-stop", 0x25AA);
        iconicIconMap.put("iconic-pause", 0x2389);
        iconicIconMap.put("iconic-to-start", 0x23EE);
        iconicIconMap.put("iconic-to-end", 0x23ED);
        iconicIconMap.put("iconic-eject", 0x23CF);
        iconicIconMap.put("iconic-target", 0x1F3AF);
        iconicIconMap.put("iconic-signal", 0x1F4F6);
        iconicIconMap.put("iconic-award", 0x1F3C9);
        iconicIconMap.put("iconic-award-empty", 0xE764);
        iconicIconMap.put("iconic-list", 0xE765);
        iconicIconMap.put("iconic-list-nested", 0xE766);
        iconicIconMap.put("iconic-bat-empty", 0xE772);
        iconicIconMap.put("iconic-bat-half", 0xE774);
        iconicIconMap.put("iconic-bat-full", 0xE774);
        iconicIconMap.put("iconic-bat-charge", 0xE775);
        iconicIconMap.put("iconic-mobile", 0x1F4F1);
        iconicIconMap.put("iconic-cd", 0x1F4BF);
        iconicIconMap.put("iconic-equalizer", 0xE795);
        iconicIconMap.put("iconic-cursor", 0xE796);
        iconicIconMap.put("iconic-aperture", 0xE797);
        iconicIconMap.put("iconic-aperture-alt", 0xE798);
        iconicIconMap.put("iconic-aperture-wheel", 0xE799);
        iconicIconMap.put("iconic-book", 0x1F4D5);
        iconicIconMap.put("iconic-book-alt", 0x1F4D4);
        iconicIconMap.put("iconic-brush", 0xE79A);
        iconicIconMap.put("iconic-brush-alt", 0xE79B);
        iconicIconMap.put("iconic-eyedropper", 0xE79C);
        iconicIconMap.put("iconic-layers", 0xE79D);
        iconicIconMap.put("iconic-layers-alt", 0xE79E);
        iconicIconMap.put("iconic-sun", 0x263C);
        iconicIconMap.put("iconic-sun-inv", 0x2600);
        iconicIconMap.put("iconic-cloud", 0x2601);
        iconicIconMap.put("iconic-rain", 0x26C6);
        iconicIconMap.put("iconic-flash", 0x26A1);
        iconicIconMap.put("iconic-moon", 0x263E);
        iconicIconMap.put("iconic-moon-inv", 0xE7A0);
        iconicIconMap.put("iconic-umbrella", 0x2602);
        iconicIconMap.put("iconic-chart-bar", 0x1F4CA);
        iconicIconMap.put("iconic-chart-pie", 0xE7A2);
        iconicIconMap.put("iconic-chart-pie-alt", 0xE7A3);
        iconicIconMap.put("iconic-key", 0x26BF);
        iconicIconMap.put("iconic-key-inv", 0x1F511);
        iconicIconMap.put("iconic-hash", 0x23);
        iconicIconMap.put("iconic-at", 0x40);
        iconicIconMap.put("iconic-pilcrow", 0xB6);
        iconicIconMap.put("iconic-dial", 0xE7A4);
    }

}
